#!/bin/bash

# A script to generate the emoji-list.lua file from unicode sources.
# Run this script from the icon-picker.nvim/scripts directory (where this file is).
# If not already present, this will download a fresh copy of the emoji-text.txt file from the unicode website.

unicode_version="15.1"
[[ -f "./emoji-test-$unicode_version.txt" ]] \
    || curl "https://unicode.org/Public/emoji/$unicode_version/emoji-test.txt" --output "emoji-test-$unicode_version.txt"
       
emoji_test_file="./emoji-test-$unicode_version.txt"
emoji_list_path="../lua/icon-picker/icons/emoji-list.lua"

cat <<EOF > $emoji_list_path
-- This file is generated by gen-emoji-table.sh 
-- Do not edit this file manually, changes will be overwritten
-- Rerun the script to regenerate this file
-- Last ran against unicode v15.1.0

local emoji_list = {
EOF

readarray -t emoji_lines <<< $( \
    grep -v ^"#" $emoji_test_file |\
    grep -v ^$ |\
    grep fully-qualified |\
    cut -d# -f2
)

for line in "${emoji_lines[@]}"; do
    emoji_icon=$(awk '{print $1}' <<< $line)
    emoji_icon=${emoji_icon%% *}
    emoji_name=$(cut -d" " -f4- <<< $line)

    echo "$emoji_icon|$emoji_name"
    echo "    [\"$emoji_name\"] = \"$emoji_icon\"," >> $emoji_list_path
done

cat <<EOF >> $emoji_list_path
}

return emoji_list
EOF
