local emoji_list = {
	["hash | keycap: # | number"] = "#️⃣",
	["asterisk | keycap: * | "] = "*️⃣",
	["zero | keycap: 0 | "] = "0️⃣",
	["one | keycap: 1 | "] = "1️⃣",
	["two | keycap: 2 | "] = "2️⃣",
	["three | keycap: 3 | "] = "3️⃣",
	["four | keycap: 4 | "] = "4️⃣",
	["five | keycap: 5 | "] = "5️⃣",
	["six | keycap: 6 | "] = "6️⃣",
	["seven | keycap: 7 | "] = "7️⃣",
	["eight | keycap: 8 | "] = "8️⃣",
	["nine | keycap: 9 | "] = "9️⃣",
	["copyright | copyright | "] = "©️",
	["registered | registered | "] = "®️",
	["bangbang | double exclamation mark | "] = "‼️",
	["interrobang | exclamation question mark | "] = "⁉️",
	["tm | trade mark | trademark"] = "™️",
	["information_source | information | "] = "ℹ️",
	["left_right_arrow | left-right arrow | "] = "↔️",
	["arrow_up_down | up-down arrow | "] = "↕️",
	["arrow_upper_left | up-left arrow | "] = "↖️",
	["arrow_upper_right | up-right arrow | "] = "↗️",
	["arrow_lower_right | down-right arrow | "] = "↘️",
	["arrow_lower_left | down-left arrow | "] = "↙️",
	["leftwards_arrow_with_hook | right arrow curving left | return"] = "↩️",
	["arrow_right_hook | left arrow curving right | "] = "↪️",
	["watch | watch | time"] = "⌚",
	["hourglass | hourglass done | time"] = "⌛",
	["keyboard | keyboard | "] = "⌨️",
	["eject_button | eject button | "] = "⏏️",
	["fast_forward | fast-forward button | "] = "⏩",
	["rewind | fast reverse button | "] = "⏪",
	["arrow_double_up | fast up button | "] = "⏫",
	["arrow_double_down | fast down button | "] = "⏬",
	["next_track_button | next track button | "] = "⏭️",
	["previous_track_button | last track button | "] = "⏮️",
	["play_or_pause_button | play or pause button | "] = "⏯️",
	["alarm_clock | alarm clock | morning"] = "⏰",
	["stopwatch | stopwatch | "] = "⏱️",
	["timer_clock | timer clock | "] = "⏲️",
	["hourglass_flowing_sand | hourglass not done | time"] = "⏳",
	["pause_button | pause button | "] = "⏸️",
	["stop_button | stop button | "] = "⏹️",
	["record_button | record button | "] = "⏺️",
	["m | circled M | "] = "Ⓜ️",
	["black_small_square | black small square | "] = "▪️",
	["white_small_square | white small square | "] = "▫️",
	["arrow_forward | play button | "] = "▶️",
	["arrow_backward | reverse button | "] = "◀️",
	["white_medium_square | white medium square | "] = "◻️",
	["black_medium_square | black medium square | "] = "◼️",
	["white_medium_small_square | white medium-small square | "] = "◽",
	["black_medium_small_square | black medium-small square | "] = "◾",
	["sunny | sun | weather"] = "☀️",
	["cloud | cloud | "] = "☁️",
	["open_umbrella | umbrella | "] = "☂️",
	["snowman_with_snow | snowman | winter christmas"] = "☃️",
	["comet | comet | "] = "☄️",
	["phone telephone | telephone | "] = "☎️",
	["ballot_box_with_check | check box with check | "] = "☑️",
	["umbrella | umbrella with rain drops | rain weather"] = "☔",
	["coffee | hot beverage | cafe espresso"] = "☕",
	["shamrock | shamrock | "] = "☘️",
	["point_up | index pointing up | "] = "☝️",
	["skull_and_crossbones | skull and crossbones | danger pirate"] = "☠️",
	["radioactive | radioactive | "] = "☢️",
	["biohazard | biohazard | "] = "☣️",
	["orthodox_cross | orthodox cross | "] = "☦️",
	["star_and_crescent | star and crescent | "] = "☪️",
	["peace_symbol | peace symbol | "] = "☮️",
	["yin_yang | yin yang | "] = "☯️",
	["wheel_of_dharma | wheel of dharma | "] = "☸️",
	["frowning_face | frowning face | "] = "☹️",
	["relaxed | smiling face | blush pleased"] = "☺️",
	["female_sign | female sign | "] = "♀️",
	["male_sign | male sign | "] = "♂️",
	["aries | Aries | "] = "♈",
	["taurus | Taurus | "] = "♉",
	["gemini | Gemini | "] = "♊",
	["cancer | Cancer | "] = "♋",
	["leo | Leo | "] = "♌",
	["virgo | Virgo | "] = "♍",
	["libra | Libra | "] = "♎",
	["scorpius | Scorpio | "] = "♏",
	["sagittarius | Sagittarius | "] = "♐",
	["capricorn | Capricorn | "] = "♑",
	["aquarius | Aquarius | "] = "♒",
	["pisces | Pisces | "] = "♓",
	["chess_pawn | chess pawn | "] = "♟️",
	["spades | spade suit | "] = "♠️",
	["clubs | club suit | "] = "♣️",
	["hearts | heart suit | "] = "♥️",
	["diamonds | diamond suit | "] = "♦️",
	["hotsprings | hot springs | "] = "♨️",
	["recycle | recycling symbol | environment green"] = "♻️",
	["infinity | infinity | "] = "♾️",
	["wheelchair | wheelchair symbol | accessibility"] = "♿",
	["hammer_and_pick | hammer and pick | "] = "⚒️",
	["anchor | anchor | ship"] = "⚓",
	["crossed_swords | crossed swords | "] = "⚔️",
	["medical_symbol | medical symbol | "] = "⚕️",
	["balance_scale | balance scale | "] = "⚖️",
	["alembic | alembic | "] = "⚗️",
	["gear | gear | "] = "⚙️",
	["atom_symbol | atom symbol | "] = "⚛️",
	["fleur_de_lis | fleur-de-lis | "] = "⚜️",
	["warning | warning | wip"] = "⚠️",
	["zap | high voltage | lightning thunder"] = "⚡",
	["transgender_symbol | transgender symbol | "] = "⚧️",
	["white_circle | white circle | "] = "⚪",
	["black_circle | black circle | "] = "⚫",
	["coffin | coffin | funeral"] = "⚰️",
	["funeral_urn | funeral urn | "] = "⚱️",
	["soccer | soccer ball | sports"] = "⚽",
	["baseball | baseball | sports"] = "⚾",
	["snowman | snowman without snow | winter"] = "⛄",
	["partly_sunny | sun behind cloud | weather cloud"] = "⛅",
	["cloud_with_lightning_and_rain | cloud with lightning and rain | "] = "⛈️",
	["ophiuchus | Ophiuchus | "] = "⛎",
	["pick | pick | "] = "⛏️",
	["rescue_worker_helmet | rescue worker’s helmet | "] = "⛑️",
	["chains | chains | "] = "⛓️",
	["no_entry | no entry | limit"] = "⛔",
	["shinto_shrine | shinto shrine | "] = "⛩️",
	["church | church | "] = "⛪",
	["mountain | mountain | "] = "⛰️",
	["parasol_on_ground | umbrella on ground | beach_umbrella"] = "⛱️",
	["fountain | fountain | "] = "⛲",
	["golf | flag in hole | "] = "⛳",
	["ferry | ferry | "] = "⛴️",
	["boat sailboat | sailboat | "] = "⛵",
	["skier | skier | "] = "⛷️",
	["ice_skate | ice skate | skating"] = "⛸️",
	["bouncing_ball_person | person bouncing ball | basketball"] = "⛹️",
	["tent | tent | camping"] = "⛺",
	["fuelpump | fuel pump | "] = "⛽",
	["scissors | scissors | cut"] = "✂️",
	["white_check_mark | check mark button | "] = "✅",
	["airplane | airplane | flight"] = "✈️",
	["envelope | envelope | letter email"] = "✉️",
	["fist_raised fist | raised fist | power"] = "✊",
	["hand raised_hand | raised hand | highfive stop"] = "✋",
	["v | victory hand | victory peace"] = "✌️",
	["writing_hand | writing hand | "] = "✍️",
	["pencil2 | pencil | "] = "✏️",
	["black_nib | black nib | "] = "✒️",
	["heavy_check_mark | check mark | "] = "✔️",
	["heavy_multiplication_x | multiply | "] = "✖️",
	["latin_cross | latin cross | "] = "✝️",
	["star_of_david | star of David | "] = "✡️",
	["sparkles | sparkles | shiny"] = "✨",
	["eight_spoked_asterisk | eight-spoked asterisk | "] = "✳️",
	["eight_pointed_black_star | eight-pointed star | "] = "✴️",
	["snowflake | snowflake | winter cold weather"] = "❄️",
	["sparkle | sparkle | "] = "❇️",
	["x | cross mark | "] = "❌",
	["negative_squared_cross_mark | cross mark button | "] = "❎",
	["question | red question mark | confused"] = "❓",
	["grey_question | white question mark | "] = "❔",
	["grey_exclamation | white exclamation mark | "] = "❕",
	["exclamation heavy_exclamation_mark | red exclamation mark | bang"] = "❗",
	["heavy_heart_exclamation | heart exclamation | "] = "❣️",
	["heart | red heart | love"] = "❤️",
	["heavy_plus_sign | plus | "] = "➕",
	["heavy_minus_sign | minus | "] = "➖",
	["heavy_division_sign | divide | "] = "➗",
	["arrow_right | right arrow | "] = "➡️",
	["curly_loop | curly loop | "] = "➰",
	["loop | double curly loop | "] = "➿",
	["arrow_heading_up | right arrow curving up | "] = "⤴️",
	["arrow_heading_down | right arrow curving down | "] = "⤵️",
	["arrow_left | left arrow | "] = "⬅️",
	["arrow_up | up arrow | "] = "⬆️",
	["arrow_down | down arrow | "] = "⬇️",
	["black_large_square | black large square | "] = "⬛",
	["white_large_square | white large square | "] = "⬜",
	["star | star | "] = "⭐",
	["o | hollow red circle | "] = "⭕",
	["wavy_dash | wavy dash | "] = "〰️",
	["part_alternation_mark | part alternation mark | "] = "〽️",
	["congratulations | Japanese “congratulations” button | "] = "㊗️",
	["secret | Japanese “secret” button | "] = "㊙️",
	["mahjong | mahjong red dragon | "] = "🀄",
	["black_joker | joker | "] = "🃏",
	["a | A button (blood type) | "] = "🅰️",
	["b | B button (blood type) | "] = "🅱️",
	["o2 | O button (blood type) | "] = "🅾️",
	["parking | P button | "] = "🅿️",
	["ab | AB button (blood type) | "] = "🆎",
	["cl | CL button | "] = "🆑",
	["cool | COOL button | "] = "🆒",
	["free | FREE button | "] = "🆓",
	["id | ID button | "] = "🆔",
	["new | NEW button | fresh"] = "🆕",
	["ng | NG button | "] = "🆖",
	["ok | OK button | yes"] = "🆗",
	["sos | SOS button | help emergency"] = "🆘",
	["up | UP! button | "] = "🆙",
	["vs | VS button | "] = "🆚",
	["ascension_island | flag: Ascension Island | "] = "🇦🇨",
	["andorra | flag: Andorra | "] = "🇦🇩",
	["united_arab_emirates | flag: United Arab Emirates | "] = "🇦🇪",
	["afghanistan | flag: Afghanistan | "] = "🇦🇫",
	["antigua_barbuda | flag: Antigua & Barbuda | "] = "🇦🇬",
	["anguilla | flag: Anguilla | "] = "🇦🇮",
	["albania | flag: Albania | "] = "🇦🇱",
	["armenia | flag: Armenia | "] = "🇦🇲",
	["angola | flag: Angola | "] = "🇦🇴",
	["antarctica | flag: Antarctica | "] = "🇦🇶",
	["argentina | flag: Argentina | "] = "🇦🇷",
	["american_samoa | flag: American Samoa | "] = "🇦🇸",
	["austria | flag: Austria | "] = "🇦🇹",
	["australia | flag: Australia | "] = "🇦🇺",
	["aruba | flag: Aruba | "] = "🇦🇼",
	["aland_islands | flag: Åland Islands | "] = "🇦🇽",
	["azerbaijan | flag: Azerbaijan | "] = "🇦🇿",
	["bosnia_herzegovina | flag: Bosnia & Herzegovina | "] = "🇧🇦",
	["barbados | flag: Barbados | "] = "🇧🇧",
	["bangladesh | flag: Bangladesh | "] = "🇧🇩",
	["belgium | flag: Belgium | "] = "🇧🇪",
	["burkina_faso | flag: Burkina Faso | "] = "🇧🇫",
	["bulgaria | flag: Bulgaria | "] = "🇧🇬",
	["bahrain | flag: Bahrain | "] = "🇧🇭",
	["burundi | flag: Burundi | "] = "🇧🇮",
	["benin | flag: Benin | "] = "🇧🇯",
	["st_barthelemy | flag: St. Barthélemy | "] = "🇧🇱",
	["bermuda | flag: Bermuda | "] = "🇧🇲",
	["brunei | flag: Brunei | "] = "🇧🇳",
	["bolivia | flag: Bolivia | "] = "🇧🇴",
	["caribbean_netherlands | flag: Caribbean Netherlands | "] = "🇧🇶",
	["brazil | flag: Brazil | "] = "🇧🇷",
	["bahamas | flag: Bahamas | "] = "🇧🇸",
	["bhutan | flag: Bhutan | "] = "🇧🇹",
	["bouvet_island | flag: Bouvet Island | "] = "🇧🇻",
	["botswana | flag: Botswana | "] = "🇧🇼",
	["belarus | flag: Belarus | "] = "🇧🇾",
	["belize | flag: Belize | "] = "🇧🇿",
	["canada | flag: Canada | "] = "🇨🇦",
	["cocos_islands | flag: Cocos (Keeling) Islands | keeling"] = "🇨🇨",
	["congo_kinshasa | flag: Congo - Kinshasa | "] = "🇨🇩",
	["central_african_republic | flag: Central African Republic | "] = "🇨🇫",
	["congo_brazzaville | flag: Congo - Brazzaville | "] = "🇨🇬",
	["switzerland | flag: Switzerland | "] = "🇨🇭",
	["cote_divoire | flag: Côte d’Ivoire | ivory"] = "🇨🇮",
	["cook_islands | flag: Cook Islands | "] = "🇨🇰",
	["chile | flag: Chile | "] = "🇨🇱",
	["cameroon | flag: Cameroon | "] = "🇨🇲",
	["cn | flag: China | china"] = "🇨🇳",
	["colombia | flag: Colombia | "] = "🇨🇴",
	["clipperton_island | flag: Clipperton Island | "] = "🇨🇵",
	["costa_rica | flag: Costa Rica | "] = "🇨🇷",
	["cuba | flag: Cuba | "] = "🇨🇺",
	["cape_verde | flag: Cape Verde | "] = "🇨🇻",
	["curacao | flag: Curaçao | "] = "🇨🇼",
	["christmas_island | flag: Christmas Island | "] = "🇨🇽",
	["cyprus | flag: Cyprus | "] = "🇨🇾",
	["czech_republic | flag: Czechia | "] = "🇨🇿",
	["de | flag: Germany | flag germany"] = "🇩🇪",
	["diego_garcia | flag: Diego Garcia | "] = "🇩🇬",
	["djibouti | flag: Djibouti | "] = "🇩🇯",
	["denmark | flag: Denmark | "] = "🇩🇰",
	["dominica | flag: Dominica | "] = "🇩🇲",
	["dominican_republic | flag: Dominican Republic | "] = "🇩🇴",
	["algeria | flag: Algeria | "] = "🇩🇿",
	["ceuta_melilla | flag: Ceuta & Melilla | "] = "🇪🇦",
	["ecuador | flag: Ecuador | "] = "🇪🇨",
	["estonia | flag: Estonia | "] = "🇪🇪",
	["egypt | flag: Egypt | "] = "🇪🇬",
	["western_sahara | flag: Western Sahara | "] = "🇪🇭",
	["eritrea | flag: Eritrea | "] = "🇪🇷",
	["es | flag: Spain | spain"] = "🇪🇸",
	["ethiopia | flag: Ethiopia | "] = "🇪🇹",
	["eu european_union | flag: European Union | "] = "🇪🇺",
	["finland | flag: Finland | "] = "🇫🇮",
	["fiji | flag: Fiji | "] = "🇫🇯",
	["falkland_islands | flag: Falkland Islands | "] = "🇫🇰",
	["micronesia | flag: Micronesia | "] = "🇫🇲",
	["faroe_islands | flag: Faroe Islands | "] = "🇫🇴",
	["fr | flag: France | france french"] = "🇫🇷",
	["gabon | flag: Gabon | "] = "🇬🇦",
	["gb uk | flag: United Kingdom | flag british"] = "🇬🇧",
	["grenada | flag: Grenada | "] = "🇬🇩",
	["georgia | flag: Georgia | "] = "🇬🇪",
	["french_guiana | flag: French Guiana | "] = "🇬🇫",
	["guernsey | flag: Guernsey | "] = "🇬🇬",
	["ghana | flag: Ghana | "] = "🇬🇭",
	["gibraltar | flag: Gibraltar | "] = "🇬🇮",
	["greenland | flag: Greenland | "] = "🇬🇱",
	["gambia | flag: Gambia | "] = "🇬🇲",
	["guinea | flag: Guinea | "] = "🇬🇳",
	["guadeloupe | flag: Guadeloupe | "] = "🇬🇵",
	["equatorial_guinea | flag: Equatorial Guinea | "] = "🇬🇶",
	["greece | flag: Greece | "] = "🇬🇷",
	["south_georgia_south_sandwich_islands | flag: South Georgia & South Sandwich Islands | "] = "🇬🇸",
	["guatemala | flag: Guatemala | "] = "🇬🇹",
	["guam | flag: Guam | "] = "🇬🇺",
	["guinea_bissau | flag: Guinea-Bissau | "] = "🇬🇼",
	["guyana | flag: Guyana | "] = "🇬🇾",
	["hong_kong | flag: Hong Kong SAR China | "] = "🇭🇰",
	["heard_mcdonald_islands | flag: Heard & McDonald Islands | "] = "🇭🇲",
	["honduras | flag: Honduras | "] = "🇭🇳",
	["croatia | flag: Croatia | "] = "🇭🇷",
	["haiti | flag: Haiti | "] = "🇭🇹",
	["hungary | flag: Hungary | "] = "🇭🇺",
	["canary_islands | flag: Canary Islands | "] = "🇮🇨",
	["indonesia | flag: Indonesia | "] = "🇮🇩",
	["ireland | flag: Ireland | "] = "🇮🇪",
	["israel | flag: Israel | "] = "🇮🇱",
	["isle_of_man | flag: Isle of Man | "] = "🇮🇲",
	["india | flag: India | "] = "🇮🇳",
	["british_indian_ocean_territory | flag: British Indian Ocean Territory | "] = "🇮🇴",
	["iraq | flag: Iraq | "] = "🇮🇶",
	["iran | flag: Iran | "] = "🇮🇷",
	["iceland | flag: Iceland | "] = "🇮🇸",
	["it | flag: Italy | italy"] = "🇮🇹",
	["jersey | flag: Jersey | "] = "🇯🇪",
	["jamaica | flag: Jamaica | "] = "🇯🇲",
	["jordan | flag: Jordan | "] = "🇯🇴",
	["jp | flag: Japan | japan"] = "🇯🇵",
	["kenya | flag: Kenya | "] = "🇰🇪",
	["kyrgyzstan | flag: Kyrgyzstan | "] = "🇰🇬",
	["cambodia | flag: Cambodia | "] = "🇰🇭",
	["kiribati | flag: Kiribati | "] = "🇰🇮",
	["comoros | flag: Comoros | "] = "🇰🇲",
	["st_kitts_nevis | flag: St. Kitts & Nevis | "] = "🇰🇳",
	["north_korea | flag: North Korea | "] = "🇰🇵",
	["kr | flag: South Korea | korea"] = "🇰🇷",
	["kuwait | flag: Kuwait | "] = "🇰🇼",
	["cayman_islands | flag: Cayman Islands | "] = "🇰🇾",
	["kazakhstan | flag: Kazakhstan | "] = "🇰🇿",
	["laos | flag: Laos | "] = "🇱🇦",
	["lebanon | flag: Lebanon | "] = "🇱🇧",
	["st_lucia | flag: St. Lucia | "] = "🇱🇨",
	["liechtenstein | flag: Liechtenstein | "] = "🇱🇮",
	["sri_lanka | flag: Sri Lanka | "] = "🇱🇰",
	["liberia | flag: Liberia | "] = "🇱🇷",
	["lesotho | flag: Lesotho | "] = "🇱🇸",
	["lithuania | flag: Lithuania | "] = "🇱🇹",
	["luxembourg | flag: Luxembourg | "] = "🇱🇺",
	["latvia | flag: Latvia | "] = "🇱🇻",
	["libya | flag: Libya | "] = "🇱🇾",
	["morocco | flag: Morocco | "] = "🇲🇦",
	["monaco | flag: Monaco | "] = "🇲🇨",
	["moldova | flag: Moldova | "] = "🇲🇩",
	["montenegro | flag: Montenegro | "] = "🇲🇪",
	["st_martin | flag: St. Martin | "] = "🇲🇫",
	["madagascar | flag: Madagascar | "] = "🇲🇬",
	["marshall_islands | flag: Marshall Islands | "] = "🇲🇭",
	["macedonia | flag: North Macedonia | "] = "🇲🇰",
	["mali | flag: Mali | "] = "🇲🇱",
	["myanmar | flag: Myanmar (Burma) | burma"] = "🇲🇲",
	["mongolia | flag: Mongolia | "] = "🇲🇳",
	["macau | flag: Macao SAR China | "] = "🇲🇴",
	["northern_mariana_islands | flag: Northern Mariana Islands | "] = "🇲🇵",
	["martinique | flag: Martinique | "] = "🇲🇶",
	["mauritania | flag: Mauritania | "] = "🇲🇷",
	["montserrat | flag: Montserrat | "] = "🇲🇸",
	["malta | flag: Malta | "] = "🇲🇹",
	["mauritius | flag: Mauritius | "] = "🇲🇺",
	["maldives | flag: Maldives | "] = "🇲🇻",
	["malawi | flag: Malawi | "] = "🇲🇼",
	["mexico | flag: Mexico | "] = "🇲🇽",
	["malaysia | flag: Malaysia | "] = "🇲🇾",
	["mozambique | flag: Mozambique | "] = "🇲🇿",
	["namibia | flag: Namibia | "] = "🇳🇦",
	["new_caledonia | flag: New Caledonia | "] = "🇳🇨",
	["niger | flag: Niger | "] = "🇳🇪",
	["norfolk_island | flag: Norfolk Island | "] = "🇳🇫",
	["nigeria | flag: Nigeria | "] = "🇳🇬",
	["nicaragua | flag: Nicaragua | "] = "🇳🇮",
	["netherlands | flag: Netherlands | "] = "🇳🇱",
	["norway | flag: Norway | "] = "🇳🇴",
	["nepal | flag: Nepal | "] = "🇳🇵",
	["nauru | flag: Nauru | "] = "🇳🇷",
	["niue | flag: Niue | "] = "🇳🇺",
	["new_zealand | flag: New Zealand | "] = "🇳🇿",
	["oman | flag: Oman | "] = "🇴🇲",
	["panama | flag: Panama | "] = "🇵🇦",
	["peru | flag: Peru | "] = "🇵🇪",
	["french_polynesia | flag: French Polynesia | "] = "🇵🇫",
	["papua_new_guinea | flag: Papua New Guinea | "] = "🇵🇬",
	["philippines | flag: Philippines | "] = "🇵🇭",
	["pakistan | flag: Pakistan | "] = "🇵🇰",
	["poland | flag: Poland | "] = "🇵🇱",
	["st_pierre_miquelon | flag: St. Pierre & Miquelon | "] = "🇵🇲",
	["pitcairn_islands | flag: Pitcairn Islands | "] = "🇵🇳",
	["puerto_rico | flag: Puerto Rico | "] = "🇵🇷",
	["palestinian_territories | flag: Palestinian Territories | "] = "🇵🇸",
	["portugal | flag: Portugal | "] = "🇵🇹",
	["palau | flag: Palau | "] = "🇵🇼",
	["paraguay | flag: Paraguay | "] = "🇵🇾",
	["qatar | flag: Qatar | "] = "🇶🇦",
	["reunion | flag: Réunion | "] = "🇷🇪",
	["romania | flag: Romania | "] = "🇷🇴",
	["serbia | flag: Serbia | "] = "🇷🇸",
	["ru | flag: Russia | russia"] = "🇷🇺",
	["rwanda | flag: Rwanda | "] = "🇷🇼",
	["saudi_arabia | flag: Saudi Arabia | "] = "🇸🇦",
	["solomon_islands | flag: Solomon Islands | "] = "🇸🇧",
	["seychelles | flag: Seychelles | "] = "🇸🇨",
	["sudan | flag: Sudan | "] = "🇸🇩",
	["sweden | flag: Sweden | "] = "🇸🇪",
	["singapore | flag: Singapore | "] = "🇸🇬",
	["st_helena | flag: St. Helena | "] = "🇸🇭",
	["slovenia | flag: Slovenia | "] = "🇸🇮",
	["svalbard_jan_mayen | flag: Svalbard & Jan Mayen | "] = "🇸🇯",
	["slovakia | flag: Slovakia | "] = "🇸🇰",
	["sierra_leone | flag: Sierra Leone | "] = "🇸🇱",
	["san_marino | flag: San Marino | "] = "🇸🇲",
	["senegal | flag: Senegal | "] = "🇸🇳",
	["somalia | flag: Somalia | "] = "🇸🇴",
	["suriname | flag: Suriname | "] = "🇸🇷",
	["south_sudan | flag: South Sudan | "] = "🇸🇸",
	["sao_tome_principe | flag: São Tomé & Príncipe | "] = "🇸🇹",
	["el_salvador | flag: El Salvador | "] = "🇸🇻",
	["sint_maarten | flag: Sint Maarten | "] = "🇸🇽",
	["syria | flag: Syria | "] = "🇸🇾",
	["swaziland | flag: Eswatini | "] = "🇸🇿",
	["tristan_da_cunha | flag: Tristan da Cunha | "] = "🇹🇦",
	["turks_caicos_islands | flag: Turks & Caicos Islands | "] = "🇹🇨",
	["chad | flag: Chad | "] = "🇹🇩",
	["french_southern_territories | flag: French Southern Territories | "] = "🇹🇫",
	["togo | flag: Togo | "] = "🇹🇬",
	["thailand | flag: Thailand | "] = "🇹🇭",
	["tajikistan | flag: Tajikistan | "] = "🇹🇯",
	["tokelau | flag: Tokelau | "] = "🇹🇰",
	["timor_leste | flag: Timor-Leste | "] = "🇹🇱",
	["turkmenistan | flag: Turkmenistan | "] = "🇹🇲",
	["tunisia | flag: Tunisia | "] = "🇹🇳",
	["tonga | flag: Tonga | "] = "🇹🇴",
	["tr | flag: Turkey | turkey"] = "🇹🇷",
	["trinidad_tobago | flag: Trinidad & Tobago | "] = "🇹🇹",
	["tuvalu | flag: Tuvalu | "] = "🇹🇻",
	["taiwan | flag: Taiwan | "] = "🇹🇼",
	["tanzania | flag: Tanzania | "] = "🇹🇿",
	["ukraine | flag: Ukraine | "] = "🇺🇦",
	["uganda | flag: Uganda | "] = "🇺🇬",
	["us_outlying_islands | flag: U.S. Outlying Islands | "] = "🇺🇲",
	["united_nations | flag: United Nations | "] = "🇺🇳",
	["us | flag: United States | flag united america"] = "🇺🇸",
	["uruguay | flag: Uruguay | "] = "🇺🇾",
	["uzbekistan | flag: Uzbekistan | "] = "🇺🇿",
	["vatican_city | flag: Vatican City | "] = "🇻🇦",
	["st_vincent_grenadines | flag: St. Vincent & Grenadines | "] = "🇻🇨",
	["venezuela | flag: Venezuela | "] = "🇻🇪",
	["british_virgin_islands | flag: British Virgin Islands | "] = "🇻🇬",
	["us_virgin_islands | flag: U.S. Virgin Islands | "] = "🇻🇮",
	["vietnam | flag: Vietnam | "] = "🇻🇳",
	["vanuatu | flag: Vanuatu | "] = "🇻🇺",
	["wallis_futuna | flag: Wallis & Futuna | "] = "🇼🇫",
	["samoa | flag: Samoa | "] = "🇼🇸",
	["kosovo | flag: Kosovo | "] = "🇽🇰",
	["yemen | flag: Yemen | "] = "🇾🇪",
	["mayotte | flag: Mayotte | "] = "🇾🇹",
	["south_africa | flag: South Africa | "] = "🇿🇦",
	["zambia | flag: Zambia | "] = "🇿🇲",
	["zimbabwe | flag: Zimbabwe | "] = "🇿🇼",
	["koko | Japanese “here” button | "] = "🈁",
	["sa | Japanese “service charge” button | "] = "🈂️",
	["u7121 | Japanese “free of charge” button | "] = "🈚",
	["u6307 | Japanese “reserved” button | "] = "🈯",
	["u7981 | Japanese “prohibited” button | "] = "🈲",
	["u7a7a | Japanese “vacancy” button | "] = "🈳",
	["u5408 | Japanese “passing grade” button | "] = "🈴",
	["u6e80 | Japanese “no vacancy” button | "] = "🈵",
	["u6709 | Japanese “not free of charge” button | "] = "🈶",
	["u6708 | Japanese “monthly amount” button | "] = "🈷️",
	["u7533 | Japanese “application” button | "] = "🈸",
	["u5272 | Japanese “discount” button | "] = "🈹",
	["u55b6 | Japanese “open for business” button | "] = "🈺",
	["ideograph_advantage | Japanese “bargain” button | "] = "🉐",
	["accept | Japanese “acceptable” button | "] = "🉑",
	["cyclone | cyclone | swirl"] = "🌀",
	["foggy | foggy | karl"] = "🌁",
	["closed_umbrella | closed umbrella | weather rain"] = "🌂",
	["night_with_stars | night with stars | "] = "🌃",
	["sunrise_over_mountains | sunrise over mountains | "] = "🌄",
	["sunrise | sunrise | "] = "🌅",
	["city_sunset | cityscape at dusk | "] = "🌆",
	["city_sunrise | sunset | "] = "🌇",
	["rainbow | rainbow | "] = "🌈",
	["bridge_at_night | bridge at night | "] = "🌉",
	["ocean | water wave | sea"] = "🌊",
	["volcano | volcano | "] = "🌋",
	["milky_way | milky way | "] = "🌌",
	["earth_africa | globe showing Europe-Africa | globe world international"] = "🌍",
	["earth_americas | globe showing Americas | globe world international"] = "🌎",
	["earth_asia | globe showing Asia-Australia | globe world international"] = "🌏",
	["globe_with_meridians | globe with meridians | world global international"] = "🌐",
	["new_moon | new moon | "] = "🌑",
	["waxing_crescent_moon | waxing crescent moon | "] = "🌒",
	["first_quarter_moon | first quarter moon | "] = "🌓",
	["moon waxing_gibbous_moon | waxing gibbous moon | "] = "🌔",
	["full_moon | full moon | "] = "🌕",
	["waning_gibbous_moon | waning gibbous moon | "] = "🌖",
	["last_quarter_moon | last quarter moon | "] = "🌗",
	["waning_crescent_moon | waning crescent moon | "] = "🌘",
	["crescent_moon | crescent moon | night"] = "🌙",
	["new_moon_with_face | new moon face | "] = "🌚",
	["first_quarter_moon_with_face | first quarter moon face | "] = "🌛",
	["last_quarter_moon_with_face | last quarter moon face | "] = "🌜",
	["full_moon_with_face | full moon face | "] = "🌝",
	["sun_with_face | sun with face | summer"] = "🌞",
	["star2 | glowing star | "] = "🌟",
	["stars | shooting star | "] = "🌠",
	["thermometer | thermometer | "] = "🌡️",
	["sun_behind_small_cloud | sun behind small cloud | "] = "🌤️",
	["sun_behind_large_cloud | sun behind large cloud | "] = "🌥️",
	["sun_behind_rain_cloud | sun behind rain cloud | "] = "🌦️",
	["cloud_with_rain | cloud with rain | "] = "🌧️",
	["cloud_with_snow | cloud with snow | "] = "🌨️",
	["cloud_with_lightning | cloud with lightning | "] = "🌩️",
	["tornado | tornado | "] = "🌪️",
	["fog | fog | "] = "🌫️",
	["wind_face | wind face | "] = "🌬️",
	["hotdog | hot dog | "] = "🌭",
	["taco | taco | "] = "🌮",
	["burrito | burrito | "] = "🌯",
	["chestnut | chestnut | "] = "🌰",
	["seedling | seedling | plant"] = "🌱",
	["evergreen_tree | evergreen tree | wood"] = "🌲",
	["deciduous_tree | deciduous tree | wood"] = "🌳",
	["palm_tree | palm tree | "] = "🌴",
	["cactus | cactus | "] = "🌵",
	["hot_pepper | hot pepper | spicy"] = "🌶️",
	["tulip | tulip | flower"] = "🌷",
	["cherry_blossom | cherry blossom | flower spring"] = "🌸",
	["rose | rose | flower"] = "🌹",
	["hibiscus | hibiscus | "] = "🌺",
	["sunflower | sunflower | "] = "🌻",
	["blossom | blossom | "] = "🌼",
	["corn | ear of corn | "] = "🌽",
	["ear_of_rice | sheaf of rice | "] = "🌾",
	["herb | herb | "] = "🌿",
	["four_leaf_clover | four leaf clover | luck"] = "🍀",
	["maple_leaf | maple leaf | canada"] = "🍁",
	["fallen_leaf | fallen leaf | autumn"] = "🍂",
	["leaves | leaf fluttering in wind | leaf"] = "🍃",
	["mushroom | mushroom | "] = "🍄",
	["tomato | tomato | "] = "🍅",
	["eggplant | eggplant | aubergine"] = "🍆",
	["grapes | grapes | "] = "🍇",
	["melon | melon | "] = "🍈",
	["watermelon | watermelon | "] = "🍉",
	["tangerine orange mandarin | tangerine | "] = "🍊",
	["lemon | lemon | "] = "🍋",
	["banana | banana | fruit"] = "🍌",
	["pineapple | pineapple | "] = "🍍",
	["apple | red apple | "] = "🍎",
	["green_apple | green apple | fruit"] = "🍏",
	["pear | pear | "] = "🍐",
	["peach | peach | "] = "🍑",
	["cherries | cherries | fruit"] = "🍒",
	["strawberry | strawberry | fruit"] = "🍓",
	["hamburger | hamburger | burger"] = "🍔",
	["pizza | pizza | "] = "🍕",
	["meat_on_bone | meat on bone | "] = "🍖",
	["poultry_leg | poultry leg | meat chicken"] = "🍗",
	["rice_cracker | rice cracker | "] = "🍘",
	["rice_ball | rice ball | "] = "🍙",
	["rice | cooked rice | "] = "🍚",
	["curry | curry rice | "] = "🍛",
	["ramen | steaming bowl | noodle"] = "🍜",
	["spaghetti | spaghetti | pasta"] = "🍝",
	["bread | bread | toast"] = "🍞",
	["fries | french fries | "] = "🍟",
	["sweet_potato | roasted sweet potato | "] = "🍠",
	["dango | dango | "] = "🍡",
	["oden | oden | "] = "🍢",
	["sushi | sushi | "] = "🍣",
	["fried_shrimp | fried shrimp | tempura"] = "🍤",
	["fish_cake | fish cake with swirl | "] = "🍥",
	["icecream | soft ice cream | "] = "🍦",
	["shaved_ice | shaved ice | "] = "🍧",
	["ice_cream | ice cream | "] = "🍨",
	["doughnut | doughnut | "] = "🍩",
	["cookie | cookie | "] = "🍪",
	["chocolate_bar | chocolate bar | "] = "🍫",
	["candy | candy | sweet"] = "🍬",
	["lollipop | lollipop | "] = "🍭",
	["custard | custard | "] = "🍮",
	["honey_pot | honey pot | "] = "🍯",
	["cake | shortcake | dessert"] = "🍰",
	["bento | bento box | "] = "🍱",
	["stew | pot of food | "] = "🍲",
	["fried_egg | cooking | breakfast"] = "🍳",
	["fork_and_knife | fork and knife | cutlery"] = "🍴",
	["tea | teacup without handle | green breakfast"] = "🍵",
	["sake | sake | "] = "🍶",
	["wine_glass | wine glass | "] = "🍷",
	["cocktail | cocktail glass | drink"] = "🍸",
	["tropical_drink | tropical drink | summer vacation"] = "🍹",
	["beer | beer mug | drink"] = "🍺",
	["beers | clinking beer mugs | drinks"] = "🍻",
	["baby_bottle | baby bottle | milk"] = "🍼",
	["plate_with_cutlery | fork and knife with plate | dining dinner"] = "🍽️",
	["champagne | bottle with popping cork | bottle bubbly celebration"] = "🍾",
	["popcorn | popcorn | "] = "🍿",
	["ribbon | ribbon | "] = "🎀",
	["gift | wrapped gift | present birthday christmas"] = "🎁",
	["birthday | birthday cake | party"] = "🎂",
	["jack_o_lantern | jack-o-lantern | halloween"] = "🎃",
	["christmas_tree | Christmas tree | "] = "🎄",
	["santa | Santa Claus | christmas"] = "🎅",
	["fireworks | fireworks | festival celebration"] = "🎆",
	["sparkler | sparkler | "] = "🎇",
	["balloon | balloon | party birthday"] = "🎈",
	["tada | party popper | hooray party"] = "🎉",
	["confetti_ball | confetti ball | "] = "🎊",
	["tanabata_tree | tanabata tree | "] = "🎋",
	["crossed_flags | crossed flags | "] = "🎌",
	["bamboo | pine decoration | "] = "🎍",
	["dolls | Japanese dolls | "] = "🎎",
	["flags | carp streamer | "] = "🎏",
	["wind_chime | wind chime | "] = "🎐",
	["rice_scene | moon viewing ceremony | "] = "🎑",
	["school_satchel | backpack | "] = "🎒",
	["mortar_board | graduation cap | education college university graduation"] = "🎓",
	["medal_military | military medal | "] = "🎖️",
	["reminder_ribbon | reminder ribbon | "] = "🎗️",
	["studio_microphone | studio microphone | podcast"] = "🎙️",
	["level_slider | level slider | "] = "🎚️",
	["control_knobs | control knobs | "] = "🎛️",
	["film_strip | film frames | "] = "🎞️",
	["tickets | admission tickets | "] = "🎟️",
	["carousel_horse | carousel horse | "] = "🎠",
	["ferris_wheel | ferris wheel | "] = "🎡",
	["roller_coaster | roller coaster | "] = "🎢",
	["fishing_pole_and_fish | fishing pole | "] = "🎣",
	["microphone | microphone | sing"] = "🎤",
	["movie_camera | movie camera | film video"] = "🎥",
	["cinema | cinema | film movie"] = "🎦",
	["headphones | headphone | music earphones"] = "🎧",
	["art | artist palette | design paint"] = "🎨",
	["tophat | top hat | hat classy"] = "🎩",
	["circus_tent | circus tent | "] = "🎪",
	["ticket | ticket | "] = "🎫",
	["clapper | clapper board | film"] = "🎬",
	["performing_arts | performing arts | theater drama"] = "🎭",
	["video_game | video game | play controller console"] = "🎮",
	["dart | bullseye | target"] = "🎯",
	["slot_machine | slot machine | "] = "🎰",
	["8ball | pool 8 ball | pool billiards"] = "🎱",
	["game_die | game die | dice gambling"] = "🎲",
	["bowling | bowling | "] = "🎳",
	["flower_playing_cards | flower playing cards | "] = "🎴",
	["musical_note | musical note | "] = "🎵",
	["notes | musical notes | music"] = "🎶",
	["saxophone | saxophone | "] = "🎷",
	["guitar | guitar | rock"] = "🎸",
	["musical_keyboard | musical keyboard | piano"] = "🎹",
	["trumpet | trumpet | "] = "🎺",
	["violin | violin | "] = "🎻",
	["musical_score | musical score | "] = "🎼",
	["running_shirt_with_sash | running shirt | marathon"] = "🎽",
	["tennis | tennis | sports"] = "🎾",
	["ski | skis | "] = "🎿",
	["basketball | basketball | sports"] = "🏀",
	["checkered_flag | chequered flag | milestone finish"] = "🏁",
	["snowboarder | snowboarder | "] = "🏂",
	["runner running | person running | exercise workout marathon"] = "🏃",
	["surfer | person surfing | "] = "🏄",
	["medal_sports | sports medal | gold winner"] = "🏅",
	["trophy | trophy | award contest winner"] = "🏆",
	["horse_racing | horse racing | "] = "🏇",
	["football | american football | sports"] = "🏈",
	["rugby_football | rugby football | "] = "🏉",
	["swimmer | person swimming | "] = "🏊",
	["weight_lifting | person lifting weights | gym workout"] = "🏋️",
	["golfing | person golfing | "] = "🏌️",
	["motorcycle | motorcycle | "] = "🏍️",
	["racing_car | racing car | "] = "🏎️",
	["cricket_game | cricket game | "] = "🏏",
	["volleyball | volleyball | "] = "🏐",
	["field_hockey | field hockey | "] = "🏑",
	["ice_hockey | ice hockey | "] = "🏒",
	["ping_pong | ping pong | "] = "🏓",
	["mountain_snow | snow-capped mountain | "] = "🏔️",
	["camping | camping | "] = "🏕️",
	["beach_umbrella | beach with umbrella | "] = "🏖️",
	["building_construction | building construction | "] = "🏗️",
	["houses | houses | "] = "🏘️",
	["cityscape | cityscape | skyline"] = "🏙️",
	["derelict_house | derelict house | "] = "🏚️",
	["classical_building | classical building | "] = "🏛️",
	["desert | desert | "] = "🏜️",
	["desert_island | desert island | "] = "🏝️",
	["national_park | national park | "] = "🏞️",
	["stadium | stadium | "] = "🏟️",
	["house | house | "] = "🏠",
	["house_with_garden | house with garden | "] = "🏡",
	["office | office building | "] = "🏢",
	["post_office | Japanese post office | "] = "🏣",
	["european_post_office | post office | "] = "🏤",
	["hospital | hospital | "] = "🏥",
	["bank | bank | "] = "🏦",
	["atm | ATM sign | "] = "🏧",
	["hotel | hotel | "] = "🏨",
	["love_hotel | love hotel | "] = "🏩",
	["convenience_store | convenience store | "] = "🏪",
	["school | school | "] = "🏫",
	["department_store | department store | "] = "🏬",
	["factory | factory | "] = "🏭",
	["izakaya_lantern lantern | red paper lantern | "] = "🏮",
	["japanese_castle | Japanese castle | "] = "🏯",
	["european_castle | castle | "] = "🏰",
	["white_flag | white flag | "] = "🏳️",
	["black_flag | black flag | "] = "🏴",
	["england | flag: England | "] = "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
	["scotland | flag: Scotland | "] = "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
	["wales | flag: Wales | "] = "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
	["rosette | rosette | "] = "🏵️",
	["label | label | tag"] = "🏷️",
	["badminton | badminton | "] = "🏸",
	["bow_and_arrow | bow and arrow | archery"] = "🏹",
	["amphora | amphora | "] = "🏺",
	["rat | rat | "] = "🐀",
	["mouse2 | mouse | "] = "🐁",
	["ox | ox | "] = "🐂",
	["water_buffalo | water buffalo | "] = "🐃",
	["cow2 | cow | "] = "🐄",
	["tiger2 | tiger | "] = "🐅",
	["leopard | leopard | "] = "🐆",
	["rabbit2 | rabbit | "] = "🐇",
	["cat2 | cat | "] = "🐈",
	["dragon | dragon | "] = "🐉",
	["crocodile | crocodile | "] = "🐊",
	["whale2 | whale | "] = "🐋",
	["snail | snail | slow"] = "🐌",
	["snake | snake | "] = "🐍",
	["racehorse | horse | speed"] = "🐎",
	["ram | ram | "] = "🐏",
	["goat | goat | "] = "🐐",
	["sheep | ewe | "] = "🐑",
	["monkey | monkey | "] = "🐒",
	["rooster | rooster | "] = "🐓",
	["chicken | chicken | "] = "🐔",
	["dog2 | dog | "] = "🐕",
	["pig2 | pig | "] = "🐖",
	["boar | boar | "] = "🐗",
	["elephant | elephant | "] = "🐘",
	["octopus | octopus | "] = "🐙",
	["shell | spiral shell | sea beach"] = "🐚",
	["bug | bug | "] = "🐛",
	["ant | ant | "] = "🐜",
	["bee honeybee | honeybee | "] = "🐝",
	["lady_beetle | lady beetle | bug"] = "🐞",
	["fish | fish | "] = "🐟",
	["tropical_fish | tropical fish | "] = "🐠",
	["blowfish | blowfish | "] = "🐡",
	["turtle | turtle | slow"] = "🐢",
	["hatching_chick | hatching chick | "] = "🐣",
	["baby_chick | baby chick | "] = "🐤",
	["hatched_chick | front-facing baby chick | "] = "🐥",
	["bird | bird | "] = "🐦",
	["penguin | penguin | "] = "🐧",
	["koala | koala | "] = "🐨",
	["poodle | poodle | dog"] = "🐩",
	["dromedary_camel | camel | desert"] = "🐪",
	["camel | two-hump camel | "] = "🐫",
	["dolphin flipper | dolphin | "] = "🐬",
	["mouse | mouse face | "] = "🐭",
	["cow | cow face | "] = "🐮",
	["tiger | tiger face | "] = "🐯",
	["rabbit | rabbit face | bunny"] = "🐰",
	["cat | cat face | pet"] = "🐱",
	["dragon_face | dragon face | "] = "🐲",
	["whale | spouting whale | sea"] = "🐳",
	["horse | horse face | "] = "🐴",
	["monkey_face | monkey face | "] = "🐵",
	["dog | dog face | pet"] = "🐶",
	["pig | pig face | "] = "🐷",
	["frog | frog | "] = "🐸",
	["hamster | hamster | pet"] = "🐹",
	["wolf | wolf | "] = "🐺",
	["bear | bear | "] = "🐻",
	["panda_face | panda | "] = "🐼",
	["pig_nose | pig nose | "] = "🐽",
	["feet paw_prints | paw prints | "] = "🐾",
	["chipmunk | chipmunk | "] = "🐿️",
	["eyes | eyes | look see watch"] = "👀",
	["eye | eye | "] = "👁️",
	["ear | ear | hear sound listen"] = "👂",
	["nose | nose | smell"] = "👃",
	["lips | mouth | kiss"] = "👄",
	["tongue | tongue | taste"] = "👅",
	["point_up_2 | backhand index pointing up | "] = "👆",
	["point_down | backhand index pointing down | "] = "👇",
	["point_left | backhand index pointing left | "] = "👈",
	["point_right | backhand index pointing right | "] = "👉",
	["fist_oncoming facepunch punch | oncoming fist | attack"] = "👊",
	["wave | waving hand | goodbye"] = "👋",
	["ok_hand | OK hand | "] = "👌",
	["+1 thumbsup | thumbs up | approve ok"] = "👍",
	["-1 thumbsdown | thumbs down | disapprove bury"] = "👎",
	["clap | clapping hands | praise applause"] = "👏",
	["open_hands | open hands | "] = "👐",
	["crown | crown | king queen royal"] = "👑",
	["womans_hat | woman’s hat | "] = "👒",
	["eyeglasses | glasses | glasses"] = "👓",
	["necktie | necktie | shirt formal"] = "👔",
	["shirt tshirt | t-shirt | "] = "👕",
	["jeans | jeans | pants"] = "👖",
	["dress | dress | "] = "👗",
	["kimono | kimono | "] = "👘",
	["bikini | bikini | beach"] = "👙",
	["womans_clothes | woman’s clothes | "] = "👚",
	["purse | purse | "] = "👛",
	["handbag | handbag | bag"] = "👜",
	["pouch | clutch bag | bag"] = "👝",
	["mans_shoe shoe | man’s shoe | "] = "👞",
	["athletic_shoe | running shoe | sneaker sport running"] = "👟",
	["high_heel | high-heeled shoe | shoe"] = "👠",
	["sandal | woman’s sandal | shoe"] = "👡",
	["boot | woman’s boot | "] = "👢",
	["footprints | footprints | feet tracks"] = "👣",
	["bust_in_silhouette | bust in silhouette | user"] = "👤",
	["busts_in_silhouette | busts in silhouette | users group team"] = "👥",
	["boy | boy | child"] = "👦",
	["girl | girl | child"] = "👧",
	["man | man | mustache father dad"] = "👨",
	["woman | woman | girls"] = "👩",
	["family | family | home parents child"] = "👪",
	["couple | woman and man holding hands | date"] = "👫",
	["two_men_holding_hands | men holding hands | couple date"] = "👬",
	["two_women_holding_hands | women holding hands | couple date"] = "👭",
	["police_officer cop | police officer | law"] = "👮",
	["dancers | people with bunny ears | bunny"] = "👯",
	["person_with_veil | person with veil | marriage wedding"] = "👰",
	["blond_haired_person | person: blond hair | "] = "👱",
	["man_with_gua_pi_mao | person with skullcap | "] = "👲",
	["person_with_turban | person wearing turban | "] = "👳",
	["older_man | old man | "] = "👴",
	["older_woman | old woman | "] = "👵",
	["baby | baby | child newborn"] = "👶",
	["construction_worker | construction worker | helmet"] = "👷",
	["princess | princess | crown royal"] = "👸",
	["japanese_ogre | ogre | monster"] = "👹",
	["japanese_goblin | goblin | "] = "👺",
	["ghost | ghost | halloween"] = "👻",
	["angel | baby angel | "] = "👼",
	["alien | alien | ufo"] = "👽",
	["space_invader | alien monster | game retro"] = "👾",
	["imp | angry face with horns | angry devil evil horns"] = "👿",
	["skull | skull | dead danger poison"] = "💀",
	["tipping_hand_person information_desk_person | person tipping hand | "] = "💁",
	["guard | guard | "] = "💂",
	["woman_dancing dancer | woman dancing | dress"] = "💃",
	["lipstick | lipstick | makeup"] = "💄",
	["nail_care | nail polish | beauty manicure"] = "💅",
	["massage | person getting massage | spa"] = "💆",
	["haircut | person getting haircut | beauty"] = "💇",
	["barber | barber pole | "] = "💈",
	["syringe | syringe | health hospital needle"] = "💉",
	["pill | pill | health medicine"] = "💊",
	["kiss | kiss mark | lipstick"] = "💋",
	["love_letter | love letter | email envelope"] = "💌",
	["ring | ring | wedding marriage engaged"] = "💍",
	["gem | gem stone | diamond"] = "💎",
	["couplekiss | kiss | "] = "💏",
	["bouquet | bouquet | flowers"] = "💐",
	["couple_with_heart | couple with heart | "] = "💑",
	["wedding | wedding | marriage"] = "💒",
	["heartbeat | beating heart | "] = "💓",
	["broken_heart | broken heart | "] = "💔",
	["two_hearts | two hearts | "] = "💕",
	["sparkling_heart | sparkling heart | "] = "💖",
	["heartpulse | growing heart | "] = "💗",
	["cupid | heart with arrow | love heart"] = "💘",
	["blue_heart | blue heart | "] = "💙",
	["green_heart | green heart | "] = "💚",
	["yellow_heart | yellow heart | "] = "💛",
	["purple_heart | purple heart | "] = "💜",
	["gift_heart | heart with ribbon | chocolates"] = "💝",
	["revolving_hearts | revolving hearts | "] = "💞",
	["heart_decoration | heart decoration | "] = "💟",
	["diamond_shape_with_a_dot_inside | diamond with a dot | "] = "💠",
	["bulb | light bulb | idea light"] = "💡",
	["anger | anger symbol | angry"] = "💢",
	["bomb | bomb | boom"] = "💣",
	["zzz | zzz | sleeping"] = "💤",
	["boom collision | collision | explode"] = "💥",
	["sweat_drops | sweat droplets | water workout"] = "💦",
	["droplet | droplet | water"] = "💧",
	["dash | dashing away | wind blow fast"] = "💨",
	["hankey poop shit | pile of poo | crap"] = "💩",
	["muscle | flexed biceps | flex bicep strong workout"] = "💪",
	["dizzy | dizzy | star"] = "💫",
	["speech_balloon | speech balloon | comment"] = "💬",
	["thought_balloon | thought balloon | thinking"] = "💭",
	["white_flower | white flower | "] = "💮",
	["100 | hundred points | score perfect"] = "💯",
	["moneybag | money bag | dollar cream"] = "💰",
	["currency_exchange | currency exchange | "] = "💱",
	["heavy_dollar_sign | heavy dollar sign | "] = "💲",
	["credit_card | credit card | subscription"] = "💳",
	["yen | yen banknote | "] = "💴",
	["dollar | dollar banknote | money"] = "💵",
	["euro | euro banknote | "] = "💶",
	["pound | pound banknote | "] = "💷",
	["money_with_wings | money with wings | dollar"] = "💸",
	["chart | chart increasing with yen | "] = "💹",
	["seat | seat | "] = "💺",
	["computer | laptop | desktop screen"] = "💻",
	["briefcase | briefcase | business"] = "💼",
	["minidisc | computer disk | "] = "💽",
	["floppy_disk | floppy disk | save"] = "💾",
	["cd | optical disk | "] = "💿",
	["dvd | dvd | "] = "📀",
	["file_folder | file folder | directory"] = "📁",
	["open_file_folder | open file folder | "] = "📂",
	["page_with_curl | page with curl | "] = "📃",
	["page_facing_up | page facing up | document"] = "📄",
	["date | calendar | calendar schedule"] = "📅",
	["calendar | tear-off calendar | schedule"] = "📆",
	["card_index | card index | "] = "📇",
	["chart_with_upwards_trend | chart increasing | graph metrics"] = "📈",
	["chart_with_downwards_trend | chart decreasing | graph metrics"] = "📉",
	["bar_chart | bar chart | stats metrics"] = "📊",
	["clipboard | clipboard | "] = "📋",
	["pushpin | pushpin | location"] = "📌",
	["round_pushpin | round pushpin | location"] = "📍",
	["paperclip | paperclip | "] = "📎",
	["straight_ruler | straight ruler | "] = "📏",
	["triangular_ruler | triangular ruler | "] = "📐",
	["bookmark_tabs | bookmark tabs | "] = "📑",
	["ledger | ledger | "] = "📒",
	["notebook | notebook | "] = "📓",
	["notebook_with_decorative_cover | notebook with decorative cover | "] = "📔",
	["closed_book | closed book | "] = "📕",
	["book open_book | open book | "] = "📖",
	["green_book | green book | "] = "📗",
	["blue_book | blue book | "] = "📘",
	["orange_book | orange book | "] = "📙",
	["books | books | library"] = "📚",
	["name_badge | name badge | "] = "📛",
	["scroll | scroll | document"] = "📜",
	["memo pencil | memo | document note"] = "📝",
	["telephone_receiver | telephone receiver | phone call"] = "📞",
	["pager | pager | "] = "📟",
	["fax | fax machine | "] = "📠",
	["satellite | satellite antenna | signal"] = "📡",
	["loudspeaker | loudspeaker | announcement"] = "📢",
	["mega | megaphone | "] = "📣",
	["outbox_tray | outbox tray | "] = "📤",
	["inbox_tray | inbox tray | "] = "📥",
	["package | package | shipping"] = "📦",
	["email e-mail | e-mail | "] = "📧",
	["incoming_envelope | incoming envelope | "] = "📨",
	["envelope_with_arrow | envelope with arrow | "] = "📩",
	["mailbox_closed | closed mailbox with lowered flag | "] = "📪",
	["mailbox | closed mailbox with raised flag | "] = "📫",
	["mailbox_with_mail | open mailbox with raised flag | "] = "📬",
	["mailbox_with_no_mail | open mailbox with lowered flag | "] = "📭",
	["postbox | postbox | "] = "📮",
	["postal_horn | postal horn | "] = "📯",
	["newspaper | newspaper | press"] = "📰",
	["iphone | mobile phone | smartphone mobile"] = "📱",
	["calling | mobile phone with arrow | call incoming"] = "📲",
	["vibration_mode | vibration mode | "] = "📳",
	["mobile_phone_off | mobile phone off | mute off"] = "📴",
	["no_mobile_phones | no mobile phones | "] = "📵",
	["signal_strength | antenna bars | wifi"] = "📶",
	["camera | camera | photo"] = "📷",
	["camera_flash | camera with flash | photo"] = "📸",
	["video_camera | video camera | "] = "📹",
	["tv | television | "] = "📺",
	["radio | radio | podcast"] = "📻",
	["vhs | videocassette | "] = "📼",
	["film_projector | film projector | "] = "📽️",
	["prayer_beads | prayer beads | "] = "📿",
	["twisted_rightwards_arrows | shuffle tracks button | shuffle"] = "🔀",
	["repeat | repeat button | loop"] = "🔁",
	["repeat_one | repeat single button | "] = "🔂",
	["arrows_clockwise | clockwise vertical arrows | "] = "🔃",
	["arrows_counterclockwise | counterclockwise arrows button | sync"] = "🔄",
	["low_brightness | dim button | "] = "🔅",
	["high_brightness | bright button | "] = "🔆",
	["mute | muted speaker | sound volume"] = "🔇",
	["speaker | speaker low volume | "] = "🔈",
	["sound | speaker medium volume | volume"] = "🔉",
	["loud_sound | speaker high volume | volume"] = "🔊",
	["battery | battery | power"] = "🔋",
	["electric_plug | electric plug | "] = "🔌",
	["mag | magnifying glass tilted left | search zoom"] = "🔍",
	["mag_right | magnifying glass tilted right | "] = "🔎",
	["lock_with_ink_pen | locked with pen | "] = "🔏",
	["closed_lock_with_key | locked with key | security"] = "🔐",
	["key | key | lock password"] = "🔑",
	["lock | locked | security private"] = "🔒",
	["unlock | unlocked | security"] = "🔓",
	["bell | bell | sound notification"] = "🔔",
	["no_bell | bell with slash | volume off"] = "🔕",
	["bookmark | bookmark | "] = "🔖",
	["link | link | "] = "🔗",
	["radio_button | radio button | "] = "🔘",
	["back | BACK arrow | "] = "🔙",
	["end | END arrow | "] = "🔚",
	["on | ON! arrow | "] = "🔛",
	["soon | SOON arrow | "] = "🔜",
	["top | TOP arrow | "] = "🔝",
	["underage | no one under eighteen | "] = "🔞",
	["keycap_ten | keycap: 10 | "] = "🔟",
	["capital_abcd | input latin uppercase | letters"] = "🔠",
	["abcd | input latin lowercase | "] = "🔡",
	["1234 | input numbers | numbers"] = "🔢",
	["symbols | input symbols | "] = "🔣",
	["abc | input latin letters | alphabet"] = "🔤",
	["fire | fire | burn"] = "🔥",
	["flashlight | flashlight | "] = "🔦",
	["wrench | wrench | tool"] = "🔧",
	["hammer | hammer | tool"] = "🔨",
	["nut_and_bolt | nut and bolt | "] = "🔩",
	["hocho knife | kitchen knife | cut chop"] = "🔪",
	["gun | water pistol | shoot weapon"] = "🔫",
	["microscope | microscope | science laboratory investigate"] = "🔬",
	["telescope | telescope | "] = "🔭",
	["crystal_ball | crystal ball | fortune"] = "🔮",
	["six_pointed_star | dotted six-pointed star | "] = "🔯",
	["beginner | Japanese symbol for beginner | "] = "🔰",
	["trident | trident emblem | "] = "🔱",
	["black_square_button | black square button | "] = "🔲",
	["white_square_button | white square button | "] = "🔳",
	["red_circle | red circle | "] = "🔴",
	["large_blue_circle | blue circle | "] = "🔵",
	["large_orange_diamond | large orange diamond | "] = "🔶",
	["large_blue_diamond | large blue diamond | "] = "🔷",
	["small_orange_diamond | small orange diamond | "] = "🔸",
	["small_blue_diamond | small blue diamond | "] = "🔹",
	["small_red_triangle | red triangle pointed up | "] = "🔺",
	["small_red_triangle_down | red triangle pointed down | "] = "🔻",
	["arrow_up_small | upwards button | "] = "🔼",
	["arrow_down_small | downwards button | "] = "🔽",
	["om | om | "] = "🕉️",
	["dove | dove | peace"] = "🕊️",
	["kaaba | kaaba | "] = "🕋",
	["mosque | mosque | "] = "🕌",
	["synagogue | synagogue | "] = "🕍",
	["menorah | menorah | "] = "🕎",
	["clock1 | one o’clock | "] = "🕐",
	["clock2 | two o’clock | "] = "🕑",
	["clock3 | three o’clock | "] = "🕒",
	["clock4 | four o’clock | "] = "🕓",
	["clock5 | five o’clock | "] = "🕔",
	["clock6 | six o’clock | "] = "🕕",
	["clock7 | seven o’clock | "] = "🕖",
	["clock8 | eight o’clock | "] = "🕗",
	["clock9 | nine o’clock | "] = "🕘",
	["clock10 | ten o’clock | "] = "🕙",
	["clock11 | eleven o’clock | "] = "🕚",
	["clock12 | twelve o’clock | "] = "🕛",
	["clock130 | one-thirty | "] = "🕜",
	["clock230 | two-thirty | "] = "🕝",
	["clock330 | three-thirty | "] = "🕞",
	["clock430 | four-thirty | "] = "🕟",
	["clock530 | five-thirty | "] = "🕠",
	["clock630 | six-thirty | "] = "🕡",
	["clock730 | seven-thirty | "] = "🕢",
	["clock830 | eight-thirty | "] = "🕣",
	["clock930 | nine-thirty | "] = "🕤",
	["clock1030 | ten-thirty | "] = "🕥",
	["clock1130 | eleven-thirty | "] = "🕦",
	["clock1230 | twelve-thirty | "] = "🕧",
	["candle | candle | "] = "🕯️",
	["mantelpiece_clock | mantelpiece clock | "] = "🕰️",
	["hole | hole | "] = "🕳️",
	["business_suit_levitating | person in suit levitating | "] = "🕴️",
	["detective | detective | sleuth"] = "🕵️",
	["dark_sunglasses | sunglasses | "] = "🕶️",
	["spider | spider | "] = "🕷️",
	["spider_web | spider web | "] = "🕸️",
	["joystick | joystick | "] = "🕹️",
	["man_dancing | man dancing | dancer"] = "🕺",
	["paperclips | linked paperclips | "] = "🖇️",
	["pen | pen | "] = "🖊️",
	["fountain_pen | fountain pen | "] = "🖋️",
	["paintbrush | paintbrush | "] = "🖌️",
	["crayon | crayon | "] = "🖍️",
	["raised_hand_with_fingers_splayed | hand with fingers splayed | "] = "🖐️",
	["middle_finger fu | middle finger | "] = "🖕",
	["vulcan_salute | vulcan salute | prosper spock"] = "🖖",
	["black_heart | black heart | "] = "🖤",
	["desktop_computer | desktop computer | "] = "🖥️",
	["printer | printer | "] = "🖨️",
	["computer_mouse | computer mouse | "] = "🖱️",
	["trackball | trackball | "] = "🖲️",
	["framed_picture | framed picture | "] = "🖼️",
	["card_index_dividers | card index dividers | "] = "🗂️",
	["card_file_box | card file box | "] = "🗃️",
	["file_cabinet | file cabinet | "] = "🗄️",
	["wastebasket | wastebasket | trash"] = "🗑️",
	["spiral_notepad | spiral notepad | "] = "🗒️",
	["spiral_calendar | spiral calendar | "] = "🗓️",
	["clamp | clamp | "] = "🗜️",
	["old_key | old key | "] = "🗝️",
	["newspaper_roll | rolled-up newspaper | press"] = "🗞️",
	["dagger | dagger | "] = "🗡️",
	["speaking_head | speaking head | "] = "🗣️",
	["left_speech_bubble | left speech bubble | "] = "🗨️",
	["right_anger_bubble | right anger bubble | "] = "🗯️",
	["ballot_box | ballot box with ballot | "] = "🗳️",
	["world_map | world map | travel"] = "🗺️",
	["mount_fuji | mount fuji | "] = "🗻",
	["tokyo_tower | Tokyo tower | "] = "🗼",
	["statue_of_liberty | Statue of Liberty | "] = "🗽",
	["japan | map of Japan | "] = "🗾",
	["moyai | moai | stone"] = "🗿",
	["grinning | grinning face | smile happy"] = "😀",
	["grin | beaming face with smiling eyes | "] = "😁",
	["joy | face with tears of joy | tears"] = "😂",
	["smiley | grinning face with big eyes | happy joy haha"] = "😃",
	["smile | grinning face with smiling eyes | happy joy laugh pleased"] = "😄",
	["sweat_smile | grinning face with sweat | hot"] = "😅",
	["laughing satisfied | grinning squinting face | happy haha"] = "😆",
	["innocent | smiling face with halo | angel"] = "😇",
	["smiling_imp | smiling face with horns | devil evil horns"] = "😈",
	["wink | winking face | flirt"] = "😉",
	["blush | smiling face with smiling eyes | proud"] = "😊",
	["yum | face savoring food | tongue lick"] = "😋",
	["relieved | relieved face | whew"] = "😌",
	["heart_eyes | smiling face with heart-eyes | love crush"] = "😍",
	["sunglasses | smiling face with sunglasses | cool"] = "😎",
	["smirk | smirking face | smug"] = "😏",
	["neutral_face | neutral face | meh"] = "😐",
	["expressionless | expressionless face | "] = "😑",
	["unamused | unamused face | meh"] = "😒",
	["sweat | downcast face with sweat | "] = "😓",
	["pensive | pensive face | "] = "😔",
	["confused | confused face | "] = "😕",
	["confounded | confounded face | "] = "😖",
	["kissing | kissing face | "] = "😗",
	["kissing_heart | face blowing a kiss | flirt"] = "😘",
	["kissing_smiling_eyes | kissing face with smiling eyes | "] = "😙",
	["kissing_closed_eyes | kissing face with closed eyes | "] = "😚",
	["stuck_out_tongue | face with tongue | "] = "😛",
	["stuck_out_tongue_winking_eye | winking face with tongue | prank silly"] = "😜",
	["stuck_out_tongue_closed_eyes | squinting face with tongue | prank"] = "😝",
	["disappointed | disappointed face | sad"] = "😞",
	["worried | worried face | nervous"] = "😟",
	["angry | angry face | mad annoyed"] = "😠",
	["rage pout | pouting face | angry"] = "😡",
	["cry | crying face | sad tear"] = "😢",
	["persevere | persevering face | struggling"] = "😣",
	["triumph | face with steam from nose | smug"] = "😤",
	["disappointed_relieved | sad but relieved face | phew sweat nervous"] = "😥",
	["frowning | frowning face with open mouth | "] = "😦",
	["anguished | anguished face | stunned"] = "😧",
	["fearful | fearful face | scared shocked oops"] = "😨",
	["weary | weary face | tired"] = "😩",
	["sleepy | sleepy face | tired"] = "😪",
	["tired_face | tired face | upset whine"] = "😫",
	["grimacing | grimacing face | "] = "😬",
	["sob | loudly crying face | sad cry bawling"] = "😭",
	["open_mouth | face with open mouth | surprise impressed wow"] = "😮",
	["hushed | hushed face | silence speechless"] = "😯",
	["cold_sweat | anxious face with sweat | nervous"] = "😰",
	["scream | face screaming in fear | horror shocked"] = "😱",
	["astonished | astonished face | amazed gasp"] = "😲",
	["flushed | flushed face | "] = "😳",
	["sleeping | sleeping face | zzz"] = "😴",
	["dizzy_face | knocked-out face | "] = "😵",
	["no_mouth | face without mouth | mute silence"] = "😶",
	["mask | face with medical mask | sick ill"] = "😷",
	["smile_cat | grinning cat with smiling eyes | "] = "😸",
	["joy_cat | cat with tears of joy | "] = "😹",
	["smiley_cat | grinning cat | "] = "😺",
	["heart_eyes_cat | smiling cat with heart-eyes | "] = "😻",
	["smirk_cat | cat with wry smile | "] = "😼",
	["kissing_cat | kissing cat | "] = "😽",
	["pouting_cat | pouting cat | "] = "😾",
	["crying_cat_face | crying cat | sad tear"] = "😿",
	["scream_cat | weary cat | horror"] = "🙀",
	["slightly_frowning_face | slightly frowning face | "] = "🙁",
	["slightly_smiling_face | slightly smiling face | "] = "🙂",
	["upside_down_face | upside-down face | "] = "🙃",
	["roll_eyes | face with rolling eyes | "] = "🙄",
	["no_good | person gesturing NO | stop halt denied"] = "🙅",
	["ok_person | person gesturing OK | "] = "🙆",
	["bow | person bowing | respect thanks"] = "🙇",
	["see_no_evil | see-no-evil monkey | monkey blind ignore"] = "🙈",
	["hear_no_evil | hear-no-evil monkey | monkey deaf"] = "🙉",
	["speak_no_evil | speak-no-evil monkey | monkey mute hush"] = "🙊",
	["raising_hand | person raising hand | "] = "🙋",
	["raised_hands | raising hands | hooray"] = "🙌",
	["frowning_person | person frowning | "] = "🙍",
	["pouting_face | person pouting | "] = "🙎",
	["pray | folded hands | please hope wish"] = "🙏",
	["rocket | rocket | ship launch"] = "🚀",
	["helicopter | helicopter | "] = "🚁",
	["steam_locomotive | locomotive | train"] = "🚂",
	["railway_car | railway car | "] = "🚃",
	["bullettrain_side | high-speed train | train"] = "🚄",
	["bullettrain_front | bullet train | train"] = "🚅",
	["train2 | train | "] = "🚆",
	["metro | metro | "] = "🚇",
	["light_rail | light rail | "] = "🚈",
	["station | station | "] = "🚉",
	["tram | tram | "] = "🚊",
	["train | tram car | "] = "🚋",
	["bus | bus | "] = "🚌",
	["oncoming_bus | oncoming bus | "] = "🚍",
	["trolleybus | trolleybus | "] = "🚎",
	["busstop | bus stop | "] = "🚏",
	["minibus | minibus | "] = "🚐",
	["ambulance | ambulance | "] = "🚑",
	["fire_engine | fire engine | "] = "🚒",
	["police_car | police car | "] = "🚓",
	["oncoming_police_car | oncoming police car | "] = "🚔",
	["taxi | taxi | "] = "🚕",
	["oncoming_taxi | oncoming taxi | "] = "🚖",
	["car red_car | automobile | "] = "🚗",
	["oncoming_automobile | oncoming automobile | "] = "🚘",
	["blue_car | sport utility vehicle | "] = "🚙",
	["truck | delivery truck | "] = "🚚",
	["articulated_lorry | articulated lorry | "] = "🚛",
	["tractor | tractor | "] = "🚜",
	["monorail | monorail | "] = "🚝",
	["mountain_railway | mountain railway | "] = "🚞",
	["suspension_railway | suspension railway | "] = "🚟",
	["mountain_cableway | mountain cableway | "] = "🚠",
	["aerial_tramway | aerial tramway | "] = "🚡",
	["ship | ship | "] = "🚢",
	["rowboat | person rowing boat | "] = "🚣",
	["speedboat | speedboat | ship"] = "🚤",
	["traffic_light | horizontal traffic light | "] = "🚥",
	["vertical_traffic_light | vertical traffic light | semaphore"] = "🚦",
	["construction | construction | wip"] = "🚧",
	["rotating_light | police car light | 911 emergency"] = "🚨",
	["triangular_flag_on_post | triangular flag | "] = "🚩",
	["door | door | "] = "🚪",
	["no_entry_sign | prohibited | block forbidden"] = "🚫",
	["smoking | cigarette | cigarette"] = "🚬",
	["no_smoking | no smoking | "] = "🚭",
	["put_litter_in_its_place | litter in bin sign | "] = "🚮",
	["do_not_litter | no littering | "] = "🚯",
	["potable_water | potable water | "] = "🚰",
	["non-potable_water | non-potable water | "] = "🚱",
	["bike | bicycle | bicycle"] = "🚲",
	["no_bicycles | no bicycles | "] = "🚳",
	["bicyclist | person biking | "] = "🚴",
	["mountain_bicyclist | person mountain biking | "] = "🚵",
	["walking | person walking | "] = "🚶",
	["no_pedestrians | no pedestrians | "] = "🚷",
	["children_crossing | children crossing | "] = "🚸",
	["mens | men’s room | "] = "🚹",
	["womens | women’s room | "] = "🚺",
	["restroom | restroom | toilet"] = "🚻",
	["baby_symbol | baby symbol | "] = "🚼",
	["toilet | toilet | wc"] = "🚽",
	["wc | water closet | toilet restroom"] = "🚾",
	["shower | shower | bath"] = "🚿",
	["bath | person taking bath | shower"] = "🛀",
	["bathtub | bathtub | "] = "🛁",
	["passport_control | passport control | "] = "🛂",
	["customs | customs | "] = "🛃",
	["baggage_claim | baggage claim | airport"] = "🛄",
	["left_luggage | left luggage | "] = "🛅",
	["couch_and_lamp | couch and lamp | "] = "🛋️",
	["sleeping_bed | person in bed | "] = "🛌",
	["shopping | shopping bags | bags"] = "🛍️",
	["bellhop_bell | bellhop bell | "] = "🛎️",
	["bed | bed | "] = "🛏️",
	["place_of_worship | place of worship | "] = "🛐",
	["stop_sign | stop sign | "] = "🛑",
	["shopping_cart | shopping cart | "] = "🛒",
	["hindu_temple | hindu temple | "] = "🛕",
	["hut | hut | "] = "🛖",
	["elevator | elevator | "] = "🛗",
	["hammer_and_wrench | hammer and wrench | "] = "🛠️",
	["shield | shield | "] = "🛡️",
	["oil_drum | oil drum | "] = "🛢️",
	["motorway | motorway | "] = "🛣️",
	["railway_track | railway track | "] = "🛤️",
	["motor_boat | motor boat | "] = "🛥️",
	["small_airplane | small airplane | flight"] = "🛩️",
	["flight_departure | airplane departure | "] = "🛫",
	["flight_arrival | airplane arrival | "] = "🛬",
	["artificial_satellite | satellite | orbit space"] = "🛰️",
	["passenger_ship | passenger ship | cruise"] = "🛳️",
	["kick_scooter | kick scooter | "] = "🛴",
	["motor_scooter | motor scooter | "] = "🛵",
	["canoe | canoe | "] = "🛶",
	["sled | sled | "] = "🛷",
	["flying_saucer | flying saucer | ufo"] = "🛸",
	["skateboard | skateboard | "] = "🛹",
	["auto_rickshaw | auto rickshaw | "] = "🛺",
	["pickup_truck | pickup truck | "] = "🛻",
	["roller_skate | roller skate | "] = "🛼",
	["orange_circle | orange circle | "] = "🟠",
	["yellow_circle | yellow circle | "] = "🟡",
	["green_circle | green circle | "] = "🟢",
	["purple_circle | purple circle | "] = "🟣",
	["brown_circle | brown circle | "] = "🟤",
	["red_square | red square | "] = "🟥",
	["blue_square | blue square | "] = "🟦",
	["orange_square | orange square | "] = "🟧",
	["yellow_square | yellow square | "] = "🟨",
	["green_square | green square | "] = "🟩",
	["purple_square | purple square | "] = "🟪",
	["brown_square | brown square | "] = "🟫",
	["pinched_fingers | pinched fingers | "] = "🤌",
	["white_heart | white heart | "] = "🤍",
	["brown_heart | brown heart | "] = "🤎",
	["pinching_hand | pinching hand | "] = "🤏",
	["zipper_mouth_face | zipper-mouth face | silence hush"] = "🤐",
	["money_mouth_face | money-mouth face | rich"] = "🤑",
	["face_with_thermometer | face with thermometer | sick"] = "🤒",
	["nerd_face | nerd face | geek glasses"] = "🤓",
	["thinking | thinking face | "] = "🤔",
	["face_with_head_bandage | face with head-bandage | hurt"] = "🤕",
	["robot | robot | "] = "🤖",
	["hugs | hugging face | "] = "🤗",
	["metal | sign of the horns | "] = "🤘",
	["call_me_hand | call me hand | "] = "🤙",
	["raised_back_of_hand | raised back of hand | "] = "🤚",
	["fist_left | left-facing fist | "] = "🤛",
	["fist_right | right-facing fist | "] = "🤜",
	["handshake | handshake | deal"] = "🤝",
	["crossed_fingers | crossed fingers | luck hopeful"] = "🤞",
	["love_you_gesture | love-you gesture | "] = "🤟",
	["cowboy_hat_face | cowboy hat face | "] = "🤠",
	["clown_face | clown face | "] = "🤡",
	["nauseated_face | nauseated face | sick barf disgusted"] = "🤢",
	["rofl | rolling on the floor laughing | lol laughing"] = "🤣",
	["drooling_face | drooling face | "] = "🤤",
	["lying_face | lying face | liar"] = "🤥",
	["facepalm | person facepalming | "] = "🤦",
	["sneezing_face | sneezing face | achoo sick"] = "🤧",
	["raised_eyebrow | face with raised eyebrow | suspicious"] = "🤨",
	["star_struck | star-struck | eyes"] = "🤩",
	["zany_face | zany face | goofy wacky"] = "🤪",
	["shushing_face | shushing face | silence quiet"] = "🤫",
	["cursing_face | face with symbols on mouth | foul"] = "🤬",
	["hand_over_mouth | face with hand over mouth | quiet whoops"] = "🤭",
	["vomiting_face | face vomiting | barf sick"] = "🤮",
	["exploding_head | exploding head | mind blown"] = "🤯",
	["pregnant_woman | pregnant woman | "] = "🤰",
	["breast_feeding | breast-feeding | nursing"] = "🤱",
	["palms_up_together | palms up together | "] = "🤲",
	["selfie | selfie | "] = "🤳",
	["prince | prince | crown royal"] = "🤴",
	["person_in_tuxedo | person in tuxedo | groom marriage wedding"] = "🤵",
	["mrs_claus | Mrs. Claus | santa"] = "🤶",
	["shrug | person shrugging | "] = "🤷",
	["cartwheeling | person cartwheeling | "] = "🤸",
	["person_fencing | person fencing | "] = "🤺",
	["wrestling | people wrestling | "] = "🤼",
	["water_polo | person playing water polo | "] = "🤽",
	["handball_person | person playing handball | "] = "🤾",
	["diving_mask | diving mask | "] = "🤿",
	["wilted_flower | wilted flower | "] = "🥀",
	["drum | drum | "] = "🥁",
	["clinking_glasses | clinking glasses | cheers toast"] = "🥂",
	["tumbler_glass | tumbler glass | whisky"] = "🥃",
	["spoon | spoon | "] = "🥄",
	["goal_net | goal net | "] = "🥅",
	["1st_place_medal | 1st place medal | gold"] = "🥇",
	["2nd_place_medal | 2nd place medal | silver"] = "🥈",
	["3rd_place_medal | 3rd place medal | bronze"] = "🥉",
	["boxing_glove | boxing glove | "] = "🥊",
	["martial_arts_uniform | martial arts uniform | "] = "🥋",
	["curling_stone | curling stone | "] = "🥌",
	["lacrosse | lacrosse | "] = "🥍",
	["softball | softball | "] = "🥎",
	["flying_disc | flying disc | "] = "🥏",
	["croissant | croissant | "] = "🥐",
	["avocado | avocado | "] = "🥑",
	["cucumber | cucumber | "] = "🥒",
	["bacon | bacon | "] = "🥓",
	["potato | potato | "] = "🥔",
	["carrot | carrot | "] = "🥕",
	["baguette_bread | baguette bread | "] = "🥖",
	["green_salad | green salad | "] = "🥗",
	["shallow_pan_of_food | shallow pan of food | paella curry"] = "🥘",
	["stuffed_flatbread | stuffed flatbread | "] = "🥙",
	["egg | egg | "] = "🥚",
	["milk_glass | glass of milk | "] = "🥛",
	["peanuts | peanuts | "] = "🥜",
	["kiwi_fruit | kiwi fruit | "] = "🥝",
	["pancakes | pancakes | "] = "🥞",
	["dumpling | dumpling | "] = "🥟",
	["fortune_cookie | fortune cookie | "] = "🥠",
	["takeout_box | takeout box | "] = "🥡",
	["chopsticks | chopsticks | "] = "🥢",
	["bowl_with_spoon | bowl with spoon | "] = "🥣",
	["cup_with_straw | cup with straw | "] = "🥤",
	["coconut | coconut | "] = "🥥",
	["broccoli | broccoli | "] = "🥦",
	["pie | pie | "] = "🥧",
	["pretzel | pretzel | "] = "🥨",
	["cut_of_meat | cut of meat | "] = "🥩",
	["sandwich | sandwich | "] = "🥪",
	["canned_food | canned food | "] = "🥫",
	["leafy_green | leafy green | "] = "🥬",
	["mango | mango | "] = "🥭",
	["moon_cake | moon cake | "] = "🥮",
	["bagel | bagel | "] = "🥯",
	["smiling_face_with_three_hearts | smiling face with hearts | love"] = "🥰",
	["yawning_face | yawning face | "] = "🥱",
	["smiling_face_with_tear | smiling face with tear | "] = "🥲",
	["partying_face | partying face | celebration birthday"] = "🥳",
	["woozy_face | woozy face | groggy"] = "🥴",
	["hot_face | hot face | heat sweating"] = "🥵",
	["cold_face | cold face | freezing ice"] = "🥶",
	["ninja | ninja | "] = "🥷",
	["disguised_face | disguised face | "] = "🥸",
	["pleading_face | pleading face | puppy eyes"] = "🥺",
	["sari | sari | "] = "🥻",
	["lab_coat | lab coat | "] = "🥼",
	["goggles | goggles | "] = "🥽",
	["hiking_boot | hiking boot | "] = "🥾",
	["flat_shoe | flat shoe | "] = "🥿",
	["crab | crab | "] = "🦀",
	["lion | lion | "] = "🦁",
	["scorpion | scorpion | "] = "🦂",
	["turkey | turkey | thanksgiving"] = "🦃",
	["unicorn | unicorn | "] = "🦄",
	["eagle | eagle | "] = "🦅",
	["duck | duck | "] = "🦆",
	["bat | bat | "] = "🦇",
	["shark | shark | "] = "🦈",
	["owl | owl | "] = "🦉",
	["fox_face | fox | "] = "🦊",
	["butterfly | butterfly | "] = "🦋",
	["deer | deer | "] = "🦌",
	["gorilla | gorilla | "] = "🦍",
	["lizard | lizard | "] = "🦎",
	["rhinoceros | rhinoceros | "] = "🦏",
	["shrimp | shrimp | "] = "🦐",
	["squid | squid | "] = "🦑",
	["giraffe | giraffe | "] = "🦒",
	["zebra | zebra | "] = "🦓",
	["hedgehog | hedgehog | "] = "🦔",
	["sauropod | sauropod | dinosaur"] = "🦕",
	["t-rex | T-Rex | dinosaur"] = "🦖",
	["cricket | cricket | "] = "🦗",
	["kangaroo | kangaroo | "] = "🦘",
	["llama | llama | "] = "🦙",
	["peacock | peacock | "] = "🦚",
	["hippopotamus | hippopotamus | "] = "🦛",
	["parrot | parrot | "] = "🦜",
	["raccoon | raccoon | "] = "🦝",
	["lobster | lobster | "] = "🦞",
	["mosquito | mosquito | "] = "🦟",
	["microbe | microbe | germ"] = "🦠",
	["badger | badger | "] = "🦡",
	["swan | swan | "] = "🦢",
	["mammoth | mammoth | "] = "🦣",
	["dodo | dodo | "] = "🦤",
	["sloth | sloth | "] = "🦥",
	["otter | otter | "] = "🦦",
	["orangutan | orangutan | "] = "🦧",
	["skunk | skunk | "] = "🦨",
	["flamingo | flamingo | "] = "🦩",
	["oyster | oyster | "] = "🦪",
	["beaver | beaver | "] = "🦫",
	["bison | bison | "] = "🦬",
	["seal | seal | "] = "🦭",
	["guide_dog | guide dog | "] = "🦮",
	["probing_cane | white cane | "] = "🦯",
	["bone | bone | "] = "🦴",
	["leg | leg | "] = "🦵",
	["foot | foot | "] = "🦶",
	["tooth | tooth | "] = "🦷",
	["superhero | superhero | "] = "🦸",
	["supervillain | supervillain | "] = "🦹",
	["safety_vest | safety vest | "] = "🦺",
	["ear_with_hearing_aid | ear with hearing aid | "] = "🦻",
	["motorized_wheelchair | motorized wheelchair | "] = "🦼",
	["manual_wheelchair | manual wheelchair | "] = "🦽",
	["mechanical_arm | mechanical arm | "] = "🦾",
	["mechanical_leg | mechanical leg | "] = "🦿",
	["cheese | cheese wedge | "] = "🧀",
	["cupcake | cupcake | "] = "🧁",
	["salt | salt | "] = "🧂",
	["beverage_box | beverage box | "] = "🧃",
	["garlic | garlic | "] = "🧄",
	["onion | onion | "] = "🧅",
	["falafel | falafel | "] = "🧆",
	["waffle | waffle | "] = "🧇",
	["butter | butter | "] = "🧈",
	["mate | mate | "] = "🧉",
	["ice_cube | ice | "] = "🧊",
	["bubble_tea | bubble tea | "] = "🧋",
	["standing_person | person standing | "] = "🧍",
	["kneeling_person | person kneeling | "] = "🧎",
	["deaf_person | deaf person | "] = "🧏",
	["monocle_face | face with monocle | "] = "🧐",
	["adult | person | "] = "🧑",
	["child | child | "] = "🧒",
	["older_adult | older person | "] = "🧓",
	["bearded_person | person: beard | "] = "🧔",
	["woman_with_headscarf | woman with headscarf | hijab"] = "🧕",
	["sauna_person | person in steamy room | steamy"] = "🧖",
	["climbing | person climbing | bouldering"] = "🧗",
	["lotus_position | person in lotus position | meditation"] = "🧘",
	["mage | mage | wizard"] = "🧙",
	["fairy | fairy | "] = "🧚",
	["vampire | vampire | "] = "🧛",
	["merperson | merperson | "] = "🧜",
	["elf | elf | "] = "🧝",
	["genie | genie | "] = "🧞",
	["zombie | zombie | "] = "🧟",
	["brain | brain | "] = "🧠",
	["orange_heart | orange heart | "] = "🧡",
	["billed_cap | billed cap | "] = "🧢",
	["scarf | scarf | "] = "🧣",
	["gloves | gloves | "] = "🧤",
	["coat | coat | "] = "🧥",
	["socks | socks | "] = "🧦",
	["red_envelope | red envelope | "] = "🧧",
	["firecracker | firecracker | "] = "🧨",
	["jigsaw | puzzle piece | "] = "🧩",
	["test_tube | test tube | "] = "🧪",
	["petri_dish | petri dish | "] = "🧫",
	["dna | dna | "] = "🧬",
	["compass | compass | "] = "🧭",
	["abacus | abacus | "] = "🧮",
	["fire_extinguisher | fire extinguisher | "] = "🧯",
	["toolbox | toolbox | "] = "🧰",
	["bricks | brick | "] = "🧱",
	["magnet | magnet | "] = "🧲",
	["luggage | luggage | "] = "🧳",
	["lotion_bottle | lotion bottle | "] = "🧴",
	["thread | thread | "] = "🧵",
	["yarn | yarn | "] = "🧶",
	["safety_pin | safety pin | "] = "🧷",
	["teddy_bear | teddy bear | "] = "🧸",
	["broom | broom | "] = "🧹",
	["basket | basket | "] = "🧺",
	["roll_of_paper | roll of paper | toilet"] = "🧻",
	["soap | soap | "] = "🧼",
	["sponge | sponge | "] = "🧽",
	["receipt | receipt | "] = "🧾",
	["nazar_amulet | nazar amulet | "] = "🧿",
	["ballet_shoes | ballet shoes | "] = "🩰",
	["one_piece_swimsuit | one-piece swimsuit | "] = "🩱",
	["swim_brief | briefs | "] = "🩲",
	["shorts | shorts | "] = "🩳",
	["thong_sandal | thong sandal | "] = "🩴",
	["drop_of_blood | drop of blood | "] = "🩸",
	["adhesive_bandage | adhesive bandage | "] = "🩹",
	["stethoscope | stethoscope | "] = "🩺",
	["yo_yo | yo-yo | "] = "🪀",
	["kite | kite | "] = "🪁",
	["parachute | parachute | "] = "🪂",
	["boomerang | boomerang | "] = "🪃",
	["magic_wand | magic wand | "] = "🪄",
	["pinata | piñata | "] = "🪅",
	["nesting_dolls | nesting dolls | "] = "🪆",
	["ringed_planet | ringed planet | "] = "🪐",
	["chair | chair | "] = "🪑",
	["razor | razor | "] = "🪒",
	["axe | axe | "] = "🪓",
	["diya_lamp | diya lamp | "] = "🪔",
	["banjo | banjo | "] = "🪕",
	["military_helmet | military helmet | "] = "🪖",
	["accordion | accordion | "] = "🪗",
	["long_drum | long drum | "] = "🪘",
	["coin | coin | "] = "🪙",
	["carpentry_saw | carpentry saw | "] = "🪚",
	["screwdriver | screwdriver | "] = "🪛",
	["ladder | ladder | "] = "🪜",
	["hook | hook | "] = "🪝",
	["mirror | mirror | "] = "🪞",
	["window | window | "] = "🪟",
	["plunger | plunger | "] = "🪠",
	["sewing_needle | sewing needle | "] = "🪡",
	["knot | knot | "] = "🪢",
	["bucket | bucket | "] = "🪣",
	["mouse_trap | mouse trap | "] = "🪤",
	["toothbrush | toothbrush | "] = "🪥",
	["headstone | headstone | "] = "🪦",
	["placard | placard | "] = "🪧",
	["rock | rock | "] = "🪨",
	["fly | fly | "] = "🪰",
	["worm | worm | "] = "🪱",
	["beetle | beetle | "] = "🪲",
	["cockroach | cockroach | "] = "🪳",
	["potted_plant | potted plant | "] = "🪴",
	["wood | wood | "] = "🪵",
	["feather | feather | "] = "🪶",
	["anatomical_heart | anatomical heart | "] = "🫀",
	["lungs | lungs | "] = "🫁",
	["people_hugging | people hugging | "] = "🫂",
	["blueberries | blueberries | "] = "🫐",
	["bell_pepper | bell pepper | "] = "🫑",
	["olive | olive | "] = "🫒",
	["flatbread | flatbread | "] = "🫓",
	["tamale | tamale | "] = "🫔",
	["fondue | fondue | "] = "🫕",
	["teapot | teapot | "] = "🫖",
	-- "⛹️‍♀️ bouncing_ball_woman basketball_woman | woman bouncing ball | ",
	-- "⛹️‍♂️ bouncing_ball_man basketball_man | man bouncing ball | ",
	-- "❤️‍🔥 heart_on_fire | heart on fire | ",
	-- "❤️‍🩹 mending_heart | mending heart | ",
	-- "🏃‍♀️ running_woman | woman running | exercise workout marathon",
	-- "🏃‍♂️ running_man | man running | exercise workout marathon",
	-- "🏄‍♀️ surfing_woman | woman surfing | ",
	-- "🏄‍♂️ surfing_man | man surfing | ",
	-- "🏊‍♀️ swimming_woman | woman swimming | ",
	-- "🏊‍♂️ swimming_man | man swimming | ",
	-- "🏋️‍♀️ weight_lifting_woman | woman lifting weights | gym workout",
	-- "🏋️‍♂️ weight_lifting_man | man lifting weights | gym workout",
	-- "🏌️‍♀️ golfing_woman | woman golfing | ",
	-- "🏌️‍♂️ golfing_man | man golfing | ",
	-- "🏳️‍⚧️ transgender_flag | transgender flag | ",
	-- "🏳️‍🌈 rainbow_flag | rainbow flag | pride",
	-- "🏴‍☠️ pirate_flag | pirate flag | ",
	-- "🐈‍⬛ black_cat | black cat | ",
	-- "🐕‍🦺 service_dog | service dog | ",
	-- "🐻‍❄️ polar_bear | polar bear | ",
	-- "👁️‍🗨️ eye_speech_bubble | eye in speech bubble | ",
	-- "👨‍⚕️ man_health_worker | man health worker | doctor nurse",
	-- "👨‍⚖️ man_judge | man judge | justice",
	-- "👨‍✈️ man_pilot | man pilot | ",
	-- "👨‍❤️‍👨 couple_with_heart_man_man | couple with heart: man, man | ",
	-- "👨‍❤️‍💋‍👨 couplekiss_man_man | kiss: man, man | ",
	-- "👨‍🌾 man_farmer | man farmer | ",
	-- "👨‍🍳 man_cook | man cook | chef",
	-- "👨‍🍼 man_feeding_baby | man feeding baby | ",
	-- "👨‍🎓 man_student | man student | graduation",
	-- "👨‍🎤 man_singer | man singer | rockstar",
	-- "👨‍🎨 man_artist | man artist | painter",
	-- "👨‍🏫 man_teacher | man teacher | school professor",
	-- "👨‍🏭 man_factory_worker | man factory worker | ",
	-- "👨‍👦 family_man_boy | family: man, boy | ",
	-- "👨‍👦‍👦 family_man_boy_boy | family: man, boy, boy | ",
	-- "👨‍👧 family_man_girl | family: man, girl | ",
	-- "👨‍👧‍👦 family_man_girl_boy | family: man, girl, boy | ",
	-- "👨‍👧‍👧 family_man_girl_girl | family: man, girl, girl | ",
	-- "👨‍👨‍👦 family_man_man_boy | family: man, man, boy | ",
	-- "👨‍👨‍👦‍👦 family_man_man_boy_boy | family: man, man, boy, boy | ",
	-- "👨‍👨‍👧 family_man_man_girl | family: man, man, girl | ",
	-- "👨‍👨‍👧‍👦 family_man_man_girl_boy | family: man, man, girl, boy | ",
	-- "👨‍👨‍👧‍👧 family_man_man_girl_girl | family: man, man, girl, girl | ",
	-- "👨‍👩‍👦 family_man_woman_boy | family: man, woman, boy | ",
	-- "👨‍👩‍👦‍👦 family_man_woman_boy_boy | family: man, woman, boy, boy | ",
	-- "👨‍👩‍👧 family_man_woman_girl | family: man, woman, girl | ",
	-- "👨‍👩‍👧‍👦 family_man_woman_girl_boy | family: man, woman, girl, boy | ",
	-- "👨‍👩‍👧‍👧 family_man_woman_girl_girl | family: man, woman, girl, girl | ",
	-- "👨‍💻 man_technologist | man technologist | coder",
	-- "👨‍💼 man_office_worker | man office worker | business",
	-- "👨‍🔧 man_mechanic | man mechanic | ",
	-- "👨‍🔬 man_scientist | man scientist | research",
	-- "👨‍🚀 man_astronaut | man astronaut | space",
	-- "👨‍🚒 man_firefighter | man firefighter | ",
	-- "👨‍🦯 man_with_probing_cane | man with white cane | ",
	-- "👨‍🦰 red_haired_man | man: red hair | ",
	-- "👨‍🦱 curly_haired_man | man: curly hair | ",
	-- "👨‍🦲 bald_man | man: bald | ",
	-- "👨‍🦳 white_haired_man | man: white hair | ",
	-- "👨‍🦼 man_in_motorized_wheelchair | man in motorized wheelchair | ",
	-- "👨‍🦽 man_in_manual_wheelchair | man in manual wheelchair | ",
	-- "👩‍⚕️ woman_health_worker | woman health worker | doctor nurse",
	-- "👩‍⚖️ woman_judge | woman judge | justice",
	-- "👩‍✈️ woman_pilot | woman pilot | ",
	-- "👩‍❤️‍👨 couple_with_heart_woman_man | couple with heart: woman, man | ",
	-- "👩‍❤️‍👩 couple_with_heart_woman_woman | couple with heart: woman, woman | ",
	-- "👩‍❤️‍💋‍👨 couplekiss_man_woman | kiss: woman, man | ",
	-- "👩‍❤️‍💋‍👩 couplekiss_woman_woman | kiss: woman, woman | ",
	-- "👩‍🌾 woman_farmer | woman farmer | ",
	-- "👩‍🍳 woman_cook | woman cook | chef",
	-- "👩‍🍼 woman_feeding_baby | woman feeding baby | ",
	-- "👩‍🎓 woman_student | woman student | graduation",
	-- "👩‍🎤 woman_singer | woman singer | rockstar",
	-- "👩‍🎨 woman_artist | woman artist | painter",
	-- "👩‍🏫 woman_teacher | woman teacher | school professor",
	-- "👩‍🏭 woman_factory_worker | woman factory worker | ",
	-- "👩‍👦 family_woman_boy | family: woman, boy | ",
	-- "👩‍👦‍👦 family_woman_boy_boy | family: woman, boy, boy | ",
	-- "👩‍👧 family_woman_girl | family: woman, girl | ",
	-- "👩‍👧‍👦 family_woman_girl_boy | family: woman, girl, boy | ",
	-- "👩‍👧‍👧 family_woman_girl_girl | family: woman, girl, girl | ",
	-- "👩‍👩‍👦 family_woman_woman_boy | family: woman, woman, boy | ",
	-- "👩‍👩‍👦‍👦 family_woman_woman_boy_boy | family: woman, woman, boy, boy | ",
	-- "👩‍👩‍👧 family_woman_woman_girl | family: woman, woman, girl | ",
	-- "👩‍👩‍👧‍👦 family_woman_woman_girl_boy | family: woman, woman, girl, boy | ",
	-- "👩‍👩‍👧‍👧 family_woman_woman_girl_girl | family: woman, woman, girl, girl | ",
	-- "👩‍💻 woman_technologist | woman technologist | coder",
	-- "👩‍💼 woman_office_worker | woman office worker | business",
	-- "👩‍🔧 woman_mechanic | woman mechanic | ",
	-- "👩‍🔬 woman_scientist | woman scientist | research",
	-- "👩‍🚀 woman_astronaut | woman astronaut | space",
	-- "👩‍🚒 woman_firefighter | woman firefighter | ",
	-- "👩‍🦯 woman_with_probing_cane | woman with white cane | ",
	-- "👩‍🦰 red_haired_woman | woman: red hair | ",
	-- "👩‍🦱 curly_haired_woman | woman: curly hair | ",
	-- "👩‍🦲 bald_woman | woman: bald | ",
	-- "👩‍🦳 white_haired_woman | woman: white hair | ",
	-- "👩‍🦼 woman_in_motorized_wheelchair | woman in motorized wheelchair | ",
	-- "👩‍🦽 woman_in_manual_wheelchair | woman in manual wheelchair | ",
	-- "👮‍♀️ policewoman | woman police officer | law cop",
	-- "👮‍♂️ policeman | man police officer | law cop",
	-- "👯‍♀️ dancing_women | women with bunny ears | bunny",
	-- "👯‍♂️ dancing_men | men with bunny ears | bunny",
	-- "👰‍♀️ woman_with_veil bride_with_veil | woman with veil | ",
	-- "👰‍♂️ man_with_veil | man with veil | ",
	-- "👱‍♀️ blond_haired_woman blonde_woman | woman: blond hair | ",
	-- "👱‍♂️ blond_haired_man | man: blond hair | ",
	-- "👳‍♀️ woman_with_turban | woman wearing turban | ",
	-- "👳‍♂️ man_with_turban | man wearing turban | ",
	-- "👷‍♀️ construction_worker_woman | woman construction worker | helmet",
	-- "👷‍♂️ construction_worker_man | man construction worker | helmet",
	-- "💁‍♀️ tipping_hand_woman sassy_woman | woman tipping hand | information",
	-- "💁‍♂️ tipping_hand_man sassy_man | man tipping hand | information",
	-- "💂‍♀️ guardswoman | woman guard | ",
	-- "💂‍♂️ guardsman | man guard | ",
	-- "💆‍♀️ massage_woman | woman getting massage | spa",
	-- "💆‍♂️ massage_man | man getting massage | spa",
	-- "💇‍♀️ haircut_woman | woman getting haircut | ",
	-- "💇‍♂️ haircut_man | man getting haircut | ",
	-- "🕵️‍♀️ female_detective | woman detective | sleuth",
	-- "🕵️‍♂️ male_detective | man detective | sleuth",
	-- "😮‍💨 face_exhaling | face exhaling | ",
	-- "😵‍💫 face_with_spiral_eyes | face with spiral eyes | ",
	-- "😶‍🌫️ face_in_clouds | face in clouds | ",
	-- "🙅‍♀️ no_good_woman ng_woman | woman gesturing NO | stop halt denied",
	-- "🙅‍♂️ no_good_man ng_man | man gesturing NO | stop halt denied",
	-- "🙆‍♀️ ok_woman | woman gesturing OK | ",
	-- "🙆‍♂️ ok_man | man gesturing OK | ",
	-- "🙇‍♀️ bowing_woman | woman bowing | respect thanks",
	-- "🙇‍♂️ bowing_man | man bowing | respect thanks",
	-- "🙋‍♀️ raising_hand_woman | woman raising hand | ",
	-- "🙋‍♂️ raising_hand_man | man raising hand | ",
	-- "🙍‍♀️ frowning_woman | woman frowning | ",
	-- "🙍‍♂️ frowning_man | man frowning | ",
	-- "🙎‍♀️ pouting_woman | woman pouting | ",
	-- "🙎‍♂️ pouting_man | man pouting | ",
	-- "🚣‍♀️ rowing_woman | woman rowing boat | ",
	-- "🚣‍♂️ rowing_man | man rowing boat | ",
	-- "🚴‍♀️ biking_woman | woman biking | ",
	-- "🚴‍♂️ biking_man | man biking | ",
	-- "🚵‍♀️ mountain_biking_woman | woman mountain biking | ",
	-- "🚵‍♂️ mountain_biking_man | man mountain biking | ",
	-- "🚶‍♀️ walking_woman | woman walking | ",
	-- "🚶‍♂️ walking_man | man walking | ",
	-- "🤦‍♀️ woman_facepalming | woman facepalming | ",
	-- "🤦‍♂️ man_facepalming | man facepalming | ",
	-- "🤵‍♀️ woman_in_tuxedo | woman in tuxedo | ",
	-- "🤵‍♂️ man_in_tuxedo | man in tuxedo | ",
	-- "🤷‍♀️ woman_shrugging | woman shrugging | ",
	-- "🤷‍♂️ man_shrugging | man shrugging | ",
	-- "🤸‍♀️ woman_cartwheeling | woman cartwheeling | ",
	-- "🤸‍♂️ man_cartwheeling | man cartwheeling | ",
	-- "🤹 juggling_person | person juggling | ",
	-- "🤹‍♀️ woman_juggling | woman juggling | ",
	-- "🤹‍♂️ man_juggling | man juggling | ",
	-- "🤼‍♀️ women_wrestling | women wrestling | ",
	-- "🤼‍♂️ men_wrestling | men wrestling | ",
	-- "🤽‍♀️ woman_playing_water_polo | woman playing water polo | ",
	-- "🤽‍♂️ man_playing_water_polo | man playing water polo | ",
	-- "🤾‍♀️ woman_playing_handball | woman playing handball | ",
	-- "🤾‍♂️ man_playing_handball | man playing handball | ",
	-- "🦸‍♀️ superhero_woman | woman superhero | ",
	-- "🦸‍♂️ superhero_man | man superhero | ",
	-- "🦹‍♀️ supervillain_woman | woman supervillain | ",
	-- "🦹‍♂️ supervillain_man | man supervillain | ",
	-- "🧍‍♀️ standing_woman | woman standing | ",
	-- "🧍‍♂️ standing_man | man standing | ",
	-- "🧎‍♀️ kneeling_woman | woman kneeling | ",
	-- "🧎‍♂️ kneeling_man | man kneeling | ",
	-- "🧏‍♀️ deaf_woman | deaf woman | ",
	-- "🧏‍♂️ deaf_man | deaf man | ",
	-- "🧑‍⚕️ health_worker | health worker | ",
	-- "🧑‍⚖️ judge | judge | ",
	-- "🧑‍✈️ pilot | pilot | ",
	-- "🧑‍🌾 farmer | farmer | ",
	-- "🧑‍🍳 cook | cook | ",
	-- "🧑‍🍼 person_feeding_baby | person feeding baby | ",
	-- "🧑‍🎄 mx_claus | mx claus | ",
	-- "🧑‍🎓 student | student | ",
	-- "🧑‍🎤 singer | singer | ",
	-- "🧑‍🎨 artist | artist | ",
	-- "🧑‍🏫 teacher | teacher | ",
	-- "🧑‍🏭 factory_worker | factory worker | ",
	-- "🧑‍💻 technologist | technologist | ",
	-- "🧑‍💼 office_worker | office worker | ",
	-- "🧑‍🔧 mechanic | mechanic | ",
	-- "🧑‍🔬 scientist | scientist | ",
	-- "🧑‍🚀 astronaut | astronaut | ",
	-- "🧑‍🚒 firefighter | firefighter | ",
	-- "🧑‍🤝‍🧑 people_holding_hands | people holding hands | couple date",
	-- "🧑‍🦯 person_with_probing_cane | person with white cane | ",
	-- "🧑‍🦰 person_red_hair | person: red hair | ",
	-- "🧑‍🦱 person_curly_hair | person: curly hair | ",
	-- "🧑‍🦲 person_bald | person: bald | ",
	-- "🧑‍🦳 person_white_hair | person: white hair | ",
	-- "🧑‍🦼 person_in_motorized_wheelchair | person in motorized wheelchair | ",
	-- "🧑‍🦽 person_in_manual_wheelchair | person in manual wheelchair | ",
	-- "🧔‍♀️ woman_beard | woman: beard | ",
	-- "🧔‍♂️ man_beard | man: beard | ",
	-- "🧖‍♀️ sauna_woman | woman in steamy room | steamy",
	-- "🧖‍♂️ sauna_man | man in steamy room | steamy",
	-- "🧗‍♀️ climbing_woman | woman climbing | bouldering",
	-- "🧗‍♂️ climbing_man | man climbing | bouldering",
	-- "🧘‍♀️ lotus_position_woman | woman in lotus position | meditation",
	-- "🧘‍♂️ lotus_position_man | man in lotus position | meditation",
	-- "🧙‍♀️ mage_woman | woman mage | wizard",
	-- "🧙‍♂️ mage_man | man mage | wizard",
	-- "🧚‍♀️ fairy_woman | woman fairy | ",
	-- "🧚‍♂️ fairy_man | man fairy | ",
	-- "🧛‍♀️ vampire_woman | woman vampire | ",
	-- "🧛‍♂️ vampire_man | man vampire | ",
	-- "🧜‍♀️ mermaid | mermaid | ",
	-- "🧜‍♂️ merman | merman | ",
	-- "🧝‍♀️ elf_woman | woman elf | ",
	-- "🧝‍♂️ elf_man | man elf | ",
	-- "🧞‍♀️ genie_woman | woman genie | ",
	-- "🧞‍♂️ genie_man | man genie | ",
	-- "🧟‍♀️ zombie_woman | woman zombie | ",
	-- "🧟‍♂️ zombie_man | man zombie | ",
}

return emoji_list
